// Code generated by port/gen-tables.mjs from the original's icons.ts, presets.ts and theme.ts; DO NOT EDIT.

package powerline_footer

type iconSet struct {
	Pi        string
	Model     string
	Folder    string
	Branch    string
	Git       string
	Github    string
	Gitlab    string
	Bitbucket string
	Tokens    string
	Context   string
	Cost      string
	Time      string
	Agents    string
	Cache     string
	Input     string
	Output    string
	Host      string
	Session   string
	Auto      string
	Warning   string
}

var nerdIcons = iconSet{
	Pi:        "\ue22c",
	Model:     "\uec19",
	Folder:    "\uf115",
	Branch:    "\uf126",
	Git:       "\uf1d3",
	Github:    "\uf09b",
	Gitlab:    "\uf296",
	Bitbucket: "\uf171",
	Tokens:    "\ue26b",
	Context:   "\uf1c0",
	Cost:      "\uf155",
	Time:      "\uf017",
	Agents:    "\uf0c0",
	Cache:     "\uf1c0",
	Input:     "\uf090",
	Output:    "\uf08b",
	Host:      "\uf109",
	Session:   "\uf550",
	Auto:      "\U000f0068",
	Warning:   "\uf071",
}

var asciiIcons = iconSet{
	Pi:        "\u03c0",
	Model:     "",
	Folder:    "dir",
	Branch:    "\u2387",
	Git:       "\u2387",
	Github:    "\u2387",
	Gitlab:    "\u2387",
	Bitbucket: "\u2387",
	Tokens:    "\u229b",
	Context:   "\u25eb",
	Cost:      "$",
	Time:      "\u25f7",
	Agents:    "AG",
	Cache:     "cache",
	Input:     "in:",
	Output:    "out:",
	Host:      "host",
	Session:   "id",
	Auto:      "AC",
	Warning:   "!",
}

// iconKeys maps theme.json icon names to the iconSet fields, in the original's order.
var iconKeys = []string{"pi", "model", "folder", "branch", "git", "github", "gitlab", "bitbucket", "tokens", "context", "cost", "time", "agents", "cache", "input", "output", "host", "session", "auto", "warning"}

func (i *iconSet) field(key string) *string {
	switch key {
	case "pi":
		return &i.Pi
	case "model":
		return &i.Model
	case "folder":
		return &i.Folder
	case "branch":
		return &i.Branch
	case "git":
		return &i.Git
	case "github":
		return &i.Github
	case "gitlab":
		return &i.Gitlab
	case "bitbucket":
		return &i.Bitbucket
	case "tokens":
		return &i.Tokens
	case "context":
		return &i.Context
	case "cost":
		return &i.Cost
	case "time":
		return &i.Time
	case "agents":
		return &i.Agents
	case "cache":
		return &i.Cache
	case "input":
		return &i.Input
	case "output":
		return &i.Output
	case "host":
		return &i.Host
	case "session":
		return &i.Session
	case "auto":
		return &i.Auto
	case "warning":
		return &i.Warning
	}
	return nil
}

type separatorChars struct {
	PowerlineLeft      string
	PowerlineRight     string
	PowerlineThinLeft  string
	PowerlineThinRight string
	Slash              string
	Pipe               string
	Block              string
	Space              string
	AsciiLeft          string
	AsciiRight         string
	Dot                string
}

var nerdSeparators = separatorChars{
	PowerlineLeft:      "\ue0b0",
	PowerlineRight:     "\ue0b2",
	PowerlineThinLeft:  "\ue0b1",
	PowerlineThinRight: "\ue0b3",
	Slash:              "/",
	Pipe:               "|",
	Block:              "\u2588",
	Space:              " ",
	AsciiLeft:          ">",
	AsciiRight:         "<",
	Dot:                "\u00b7",
}

var asciiSeparators = separatorChars{
	PowerlineLeft:      ">",
	PowerlineRight:     "<",
	PowerlineThinLeft:  "|",
	PowerlineThinRight: "|",
	Slash:              "/",
	Pipe:               "|",
	Block:              "#",
	Space:              " ",
	AsciiLeft:          ">",
	AsciiRight:         "<",
	Dot:                ".",
}

var thinkingTextUnicode = map[string]string{
	"minimal": "[min]",
	"low":     "[low]",
	"medium":  "[med]",
	"high":    "[high]",
	"xhigh":   "[xhi]",
}

var thinkingTextNerd = map[string]string{
	"minimal": "\uf0e7 min",
	"low":     "\uf10c low",
	"medium":  "\uf192 med",
	"high":    "\uf111 high",
	"xhigh":   "\uf06d xhi",
}

// piThemeTokens are the ThemeColor tokens of Pi 1.0.0: its Theme.fg throws on any other.
var piThemeTokens = []string{"accent", "border", "borderAccent", "borderMuted", "success", "error", "warning", "muted", "dim", "text", "thinkingText", "scrollbarTrack", "scrollbarThumb", "searchMatchText", "userMessageText", "customMessageText", "customMessageLabel", "toolTitle", "toolOutput", "mdHeading", "mdLink", "mdLinkUrl", "mdCode", "mdCodeBlock", "mdCodeBlockBorder", "mdQuote", "mdQuoteBorder", "mdHr", "mdListBullet", "toolDiffAdded", "toolDiffRemoved", "toolDiffContext", "syntaxComment", "syntaxKeyword", "syntaxFunction", "syntaxVariable", "syntaxString", "syntaxNumber", "syntaxType", "syntaxOperator", "syntaxPunctuation", "thinkingOff", "thinkingMinimal", "thinkingLow", "thinkingMedium", "thinkingHigh", "thinkingXhigh", "thinkingMax", "bashMode"}

// semanticColors lists the semantic color names in the original's order.
var semanticColors = []string{"model", "shellMode", "path", "gitDirty", "gitClean", "thinking", "thinkingMinimal", "thinkingLow", "thinkingMedium", "thinkingHigh", "thinkingXhigh", "thinkingMax", "context", "contextWarn", "contextError", "cost", "tokens", "queue", "separator", "border"}

var defaultColors = colorScheme{
	"model":           "#d787af",
	"shellMode":       "accent",
	"path":            "#00afaf",
	"gitDirty":        "warning",
	"gitClean":        "success",
	"thinking":        "thinkingOff",
	"thinkingMinimal": "thinkingMinimal",
	"thinkingLow":     "thinkingLow",
	"thinkingMedium":  "thinkingMedium",
	"thinkingHigh":    "rainbow",
	"thinkingXhigh":   "rainbow",
	"thinkingMax":     "rainbow",
	"context":         "dim",
	"contextWarn":     "warning",
	"contextError":    "error",
	"cost":            "text",
	"tokens":          "muted",
	"queue":           "accent",
	"separator":       "dim",
	"border":          "borderMuted",
}

var presetNames = []string{"default", "minimal", "compact", "full", "nerd", "ascii"}

var presets = map[string]presetDef{
	"default": {
		left: []string{"model", "thinking", "shell_mode", "path", "git", "queue", "context_pct", "cache_read", "cost"}, right: []string{}, secondary: []string{"extension_statuses"},
		separator: "powerline-thin",
		colors: colorScheme{
			"model":           "#d787af",
			"shellMode":       "accent",
			"path":            "#00afaf",
			"gitDirty":        "warning",
			"gitClean":        "success",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "text",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Model: &modelOptions{ShowThinkingLevel: ptr(false)},
			Path:  &pathOptions{Mode: ptr("basename")},
			Git:   &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(true), ShowUnstaged: ptr(true), ShowUntracked: ptr(true)},
		},
	},
	"minimal": {
		left: []string{"shell_mode", "path", "git"}, right: []string{"context_pct"}, secondary: []string{},
		separator: "slash",
		colors: colorScheme{
			"model":           "text",
			"shellMode":       "accent",
			"path":            "text",
			"gitDirty":        "warning",
			"gitClean":        "dim",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "text",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Path: &pathOptions{Mode: ptr("basename")},
			Git:  &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(false), ShowUnstaged: ptr(false), ShowUntracked: ptr(false)},
		},
	},
	"compact": {
		left: []string{"model", "shell_mode", "git"}, right: []string{"queue", "cost", "context_pct"}, secondary: []string{},
		separator: "powerline-thin",
		colors: colorScheme{
			"model":           "#d787af",
			"shellMode":       "accent",
			"path":            "#00afaf",
			"gitDirty":        "warning",
			"gitClean":        "success",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "text",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Model: &modelOptions{ShowThinkingLevel: ptr(false)},
			Git:   &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(true), ShowUnstaged: ptr(true), ShowUntracked: ptr(false)},
		},
	},
	"full": {
		left: []string{"hostname", "model", "thinking", "shell_mode", "path", "git", "queue", "subagents"}, right: []string{"token_in", "token_out", "cache_read", "cost", "context_pct", "time_spent", "time", "extension_statuses"}, secondary: []string{},
		separator: "powerline",
		colors: colorScheme{
			"model":           "#d787af",
			"shellMode":       "accent",
			"path":            "#00afaf",
			"gitDirty":        "warning",
			"gitClean":        "success",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "text",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Model: &modelOptions{ShowThinkingLevel: ptr(false)},
			Path:  &pathOptions{Mode: ptr("abbreviated"), MaxLength: ptr(50)},
			Git:   &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(true), ShowUnstaged: ptr(true), ShowUntracked: ptr(true)},
			Time:  &timeOptions{Format: ptr("24h"), ShowSeconds: ptr(false)},
		},
	},
	"nerd": {
		left: []string{"hostname", "model", "thinking", "shell_mode", "path", "git", "queue", "session", "subagents"}, right: []string{"token_in", "token_out", "cache_read", "cache_write", "cost", "context_pct", "context_total", "time_spent", "time", "extension_statuses"}, secondary: []string{},
		separator: "powerline",
		colors: colorScheme{
			"model":           "accent",
			"shellMode":       "accent",
			"path":            "success",
			"gitDirty":        "warning",
			"gitClean":        "success",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "warning",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Model: &modelOptions{ShowThinkingLevel: ptr(false)},
			Path:  &pathOptions{Mode: ptr("abbreviated"), MaxLength: ptr(60)},
			Git:   &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(true), ShowUnstaged: ptr(true), ShowUntracked: ptr(true)},
			Time:  &timeOptions{Format: ptr("24h"), ShowSeconds: ptr(true)},
		},
	},
	"ascii": {
		left: []string{"model", "shell_mode", "path", "git"}, right: []string{"queue", "token_total", "cost", "context_pct"}, secondary: []string{},
		separator: "ascii",
		colors: colorScheme{
			"model":           "text",
			"shellMode":       "accent",
			"path":            "text",
			"gitDirty":        "warning",
			"gitClean":        "dim",
			"thinking":        "thinkingOff",
			"thinkingMinimal": "thinkingMinimal",
			"thinkingLow":     "thinkingLow",
			"thinkingMedium":  "thinkingMedium",
			"thinkingHigh":    "rainbow",
			"thinkingXhigh":   "rainbow",
			"thinkingMax":     "rainbow",
			"context":         "dim",
			"contextWarn":     "warning",
			"contextError":    "error",
			"cost":            "text",
			"tokens":          "muted",
			"queue":           "accent",
			"separator":       "dim",
			"border":          "borderMuted",
		},
		options: segmentOptions{
			Model: &modelOptions{ShowThinkingLevel: ptr(true)},
			Path:  &pathOptions{Mode: ptr("abbreviated"), MaxLength: ptr(40)},
			Git:   &gitOptions{ShowBranch: ptr(true), ShowStaged: ptr(true), ShowUnstaged: ptr(true), ShowUntracked: ptr(true)},
		},
	},
}
