#!/usr/bin/env python3
"""Generates port/mutations.json: one deliberate defect per behavior. Each `find` must occur exactly once in its file (checked
here), so a mutation never silently applies to the wrong place."""
import json, os, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "extensions", "pi-permission-system")
M = []


def m(name, file, find, replace):
    M.append({"name": name, "file": file, "find": find, "replace": replace})



# wildcard.go
m("home-slash", "wildcard.go", 'strings.HasPrefix(rest, "/")', 'strings.HasPrefix(rest, "//")')
m("home-backslash", "wildcard.go", "strings.HasPrefix(rest, `\\`)", "false")
m("home-bare", "wildcard.go", 'if rest == "" {\n\t\treturn homeDir()', 'if rest == "" {\n\t\treturn ""')
m("fold-separators", "wildcard.go", 'strings.ReplaceAll(v, "/", `\\`)', 'strings.ReplaceAll(v, "/", "/")')
m("tail-suffix", "wildcard.go", 'strings.HasSuffix(expanded, " *")', 'strings.HasSuffix(expanded, " ?")')
m("tail-match", "wildcard.go", "if c.tail {", "if false {")
m("question-mark", "wildcard.go", "case '?':", "case '!':")
m("star", "wildcard.go", "case '*':\n\t\t\tc.toks", "case '+':\n\t\t\tc.toks")
m("canonical-ascii", "wildcard.go", "up > 0xFFFF || (u >= 128 && up < 128)", "up > 0xFFFF")
m("case-insensitive", "wildcard.go", "ci := c.opts != nil && c.opts.CaseInsensitive", "ci := false")
m("last-match", "wildcard.go", "for i := len(patterns) - 1; i >= 0; i-- {", "for i := 0; i < len(patterns); i++ {")
m("names-trim", "wildcard.go", "n = jsTrim(n)", "_ = jsTrim(n)")
m("names-skip-empty", "wildcard.go", 'if n == "" {\n\t\t\tcontinue', 'if false {\n\t\t\tcontinue')
m("glob-tail-star", "wildcard.go", "for p < len(toks) && toks[p].kind == tokStar {\n\t\tp++\n\t}\n\treturn p == len(toks)", "return p == len(toks)")
m("matches-fold-value", "wildcard.go", "v := utf16.Encode([]rune(foldSeparators(value, c.opts)))", "v := utf16.Encode([]rune(value))")
m("pattern-utf16", "wildcard.go", "for _, u := range utf16.Encode([]rune(expanded)) {", "for _, u := range []uint16(nil) {")

# rule.go
m("surface-path", "rule.go", '"path": true, "external_directory": true,\n\t"path_read"', '"external_directory": true,\n\t"path_read"')
m("surface-options-only-path", "rule.go", "if pathSurfaces[surface] {\n\t\treturn f.MatchOptions", "if !pathSurfaces[surface] {\n\t\treturn f.MatchOptions")
m("rule-surface-match", "rule.go", "return WildcardMatch(r.Surface, surface, nil) && WildcardMatch(r.Pattern", "return WildcardMatch(r.Surface, surface, nil) || WildcardMatch(r.Pattern")
m("yolo-rewrite", "rule.go", 'if r.Action == "ask" {\n\t\t\tr.Action, r.Origin = "allow", "yolo"', 'if r.Action != "ask" {\n\t\t\tr.Action, r.Origin = "allow", "yolo"')
m("yolo-origin", "rule.go", 'r.Action, r.Origin = "allow", "yolo"', 'r.Action, r.Origin = "allow", "builtin"')
m("floor-rewrite", "rule.go", 'if r.Action == "allow" {\n\t\t\tr.Action, r.Origin = "ask", "fail-closed"', 'if r.Action != "allow" {\n\t\t\tr.Action, r.Origin = "ask", "fail-closed"')
m("evaluate-default", "rule.go", 'defaultAction = "ask"', 'defaultAction = "deny"')
m("evaluate-default-origin", "rule.go", 'Action: defaultAction, Origin: "builtin"}', 'Action: defaultAction, Origin: "config"}')
m("evaluate-last", "rule.go", "for i := len(rules) - 1; i >= 0; i-- {\n\t\tif pred(rules[i]) {", "for i := 0; i < len(rules); i++ {\n\t\tif pred(rules[i]) {")
m("denied-catchall-probe", "rule.go", 'probes := []string{"*"}', "probes := []string{}")
m("denied-home-probe", "rule.go", "p := expandHomePath(r.Pattern)", "p := r.Pattern")
m("denied-test", "rule.go", 'if Evaluate(surface, v, rules, f, "").Action != "deny" {', 'if Evaluate(surface, v, rules, f, "").Action == "deny" {')
m("restrictive-deny-short", "rule.go", 'if r.Action == "deny" {\n\t\t\treturn &Found{r, v}', 'if r.Action == "denyx" {\n\t\t\treturn &Found{r, v}')
m("restrictive-ask-first", "rule.go", 'worst.Rule.Action != "ask"', 'worst.Rule.Action == "ask"')
m("any-fallback", "rule.go", 'fallback := "*"', 'fallback := ""')
m("any-first-value", "rule.go", "fallback = values[0]", 'fallback = "*"')
m("any-reported-value", "rule.go", "\t\tfor _, v := range values {\n\t\t\tif ruleMatches(r, surface, v, f) {\n\t\t\t\treturn Found{r, v}", "\t\tfor _, v := range values[:0] {\n\t\t\tif ruleMatches(r, surface, v, f) {\n\t\t\t\treturn Found{r, v}")
m("restrictiveness-rank", "rule.go", '"deny": 2}', '"deny": 1}')
m("restrictive-tie", "rule.go", "if restrictiveness[r.State] > restrictiveness[worst.State] {", "if restrictiveness[r.State] >= restrictiveness[worst.State] {")
m("pick-empty", "rule.go", "if len(results) == 0 {\n\t\treturn nil", "if len(results) == 1 {\n\t\treturn nil")
m("merge-both-objects", "rule.go", "if bok && vok {", "if bok || vok {")
m("merge-replace", "rule.go", "\t\t} else {\n\t\t\tmerged.set(k, v)\n\t\t}", "\t\t} else {\n\t\t\tmerged.set(k, merged.vals[k])\n\t\t}")
m("scope-skip", "rule.go", "if sc.Permission == nil {\n\t\t\tcontinue", "if sc.Permission != nil {\n\t\t\tcontinue")
m("scope-string-origin", "rule.go", 'so["*"] = sc.Name', 'so["*"] = "x"')
m("scope-object-origin", "rule.go", "so[p] = sc.Name", 'so[p] = "x"')
m("scope-merged-origin", "rule.go", "origins[surface][p] = sc.Name", 'origins[surface][p] = "x"')
m("scope-sugar", "rule.go", "permission := ExpandDirectionalSugar(sc.Permission)", "permission := sc.Permission")
m("sugar-family", "rule.go", 'map[string]bool{"path": true, "external_directory": true}', 'map[string]bool{"path": true}')
m("sugar-explicit-after", "rule.go", "if _, has := ep.vals[k]; !has {\n\t\t\tout.set(k, sp.vals[k])", "if _, has := ep.vals[k]; has {\n\t\t\tout.set(k, sp.vals[k])")
m("sugar-undefined", "rule.go", "if _, u := value.(undef); u {\n\t\t\tcontinue\n\t\t}\n\t\tif !directionalFamilies", "if _, u := value.(undef); !u {\n\t\t\tcontinue\n\t\t}\n\t\tif !directionalFamilies")
m("sugar-copy", "rule.go", "return o.clone()\n\t\t}\n\t\treturn sugar", "return o\n\t\t}\n\t\treturn sugar")
m("state-deny", "rule.go", 's == "allow" || s == "deny" || s == "ask")', 's == "allow" || s == "ask")')
m("deny-reason-action", "rule.go", 'if a, _ := o.vals["action"].(string); a != "deny" {', 'if a, _ := o.vals["action"].(string); a == "deny" {')
m("deny-reason-type", "rule.go", "s, isStr := r.(string)\n\tif !isStr {\n\t\treturn nil, false", "s, isStr := r.(string)\n\tif !isStr {\n\t\treturn nil, true")
m("normalize-array", "rule.go", "Pattern: itoa(i)", "Pattern: itoa(i + 1)")
m("mcp-name-sep", "rule.go", "return sep > 0 && sep+2 < len(rest)", "return sep >= 0 && sep+2 < len(rest)")
m("mcp-name-tool", "rule.go", "return sep > 0 && sep+2 < len(rest)", "return sep > 0 && sep+2 <= len(rest)")
m("mcp-wildcard-key", "rule.go", 'strings.ContainsAny(key, "*?")', 'strings.ContainsAny(key, "*")')
m("relocate-catchall", "rule.go", 'if r.Pattern == "*" && canNamePiMcpTool(r.Surface) {', "if canNamePiMcpTool(r.Surface) {")

# config.go
m("yolo-flag", "config.go", 'c.Yolo, _ = root.vals["yoloMode"].(bool)', "c.Yolo = false")
m("config-permission-object", "config.go", 'if perm := root.obj("permission"); perm != nil {', 'if perm := root.obj("permissionx"); perm != nil {')
m("config-issue", "config.go", "return Config{Issue: \"Failed to read config at '\" + path + \"': \" + err.Error()}\n\t}\n\tif issues", "return Config{}\n\t}\n\tif issues")
m("permissive-value", "config.go", 's, _ := permission.vals["*"].(string); s != "allow"', 's, _ := permission.vals["*"].(string); s != "ask"')
m("permissive-string", "config.go", "case string:\n\t\treturn \"\"\n\tcase *jsObject:", "case *jsObject:")
m("permissive-star-key", "config.go", 'if _, has := bash.vals["*"]; has {', 'if _, has := bash.vals["*x"]; has {')
m("universal-fallback", "config.go", "universal = s", 'universal = map[string]string{"allow": "deny", "deny": "allow", "ask": "ask"}[s]')
m("universal-excluded", "config.go", 'if k != "*" {', "if true {")
m("config-layer", "config.go", 'r.Layer, r.Origin = "config", "global"', 'r.Layer, r.Origin = "default", "global"')
m("universal-origin", "config.go", 'Layer: "default", Origin: originOf(permission)}}', 'Layer: "default", Origin: "builtin"}}')
m("yolo-policy", "config.go", "if c.Yolo {\n\t\trules = RewriteAsksToYolo(rules)", "if false {\n\t\trules = RewriteAsksToYolo(rules)")
m("simple-assignment", "config.go", 'return !strings.Contains(first, "=")', 'return !strings.Contains(first, "==")')
m("simple-leading-space", "config.go", 'strings.HasPrefix(cmd, " ") || strings.HasSuffix(cmd, " ")', 'strings.HasSuffix(cmd, " ")')
m("simple-trailing-space", "config.go", 'strings.HasPrefix(cmd, " ") || strings.HasSuffix(cmd, " ")', 'strings.HasPrefix(cmd, " ")')
m("simple-chars", "config.go", 'strings.ContainsRune("_./:=@%+,- ", r)', 'strings.ContainsRune("_./:=@%+,- |", r)')
m("outcome-rule-clause", "config.go", 'if r.Layer == "config" || r.Layer == "session" {', "if false {")
m("outcome-reason", "config.go", 'if r.Reason != nil && *r.Reason != "" {', "if false {")
m("outcome-ask", "config.go", 'case "ask":\n\t\treturn asked(surface)', 'case "ask":\n\t\treturn Verdict{}')
m("path-family-write", "config.go", '"external_directory_read", "external_directory_write"}', '"external_directory_read"}')
m("path-family-patterns", "config.go", "if p.valuePatterns(s) {\n\t\t\treturn false", "if false {\n\t\t\treturn false")
m("path-family-constant", "config.go", 'if p.constant(s).Action != "allow" {', 'if p.constant(s).Action == "deny" {')
m("bash-needs-path-family", "config.go", "\t\tif ok, why := p.pathFamilyAllows(name); !ok {\n\t\t\treturn unsupported(name, why)\n\t\t}\n\t\treturn p.decideBash(cmd)", "\t\treturn p.decideBash(cmd)")
m("bash-patterns-constant", "bash.go", "if patterns {\n\t\t\tr = Evaluate", "if !patterns {\n\t\t\tr = Evaluate")
m("skill-surface", "config.go", 'case name == "mcp", name == "skill", isPiMcpToolName(name):', 'case name == "mcp", isPiMcpToolName(name):')
m("mcp-surface", "config.go", 'case name == "mcp", name == "skill", isPiMcpToolName(name):', 'case name == "skill", isPiMcpToolName(name):')
m("path-tool-patterns", "config.go", "if p.valuePatterns(name) {\n\t\t\treturn unsupported(name, \"the rules for it", "if false {\n\t\t\treturn unsupported(name, \"the rules for it")
m("path-tool-family", "config.go", "\t\tif ok, why := p.pathFamilyAllows(name); !ok {\n\t\t\treturn unsupported(name, why)\n\t\t}\n\t\treturn p.outcome(name, p.constant(name))", "\t\treturn p.outcome(name, p.constant(name))")
m("tool-trim", "config.go", "name := jsTrim(tool)\n\tswitch {", "name := tool\n\tswitch {")
m("denied-mcp", "config.go", "if isPiMcpToolName(name) {\n\t\treturn false", "if false {\n\t\treturn false")
m("denied-trim", "config.go", "name := jsTrim(tool)\n\tif isPiMcpToolName(name) {", "name := tool\n\tif isPiMcpToolName(name) {")
m("agent-dir-abs", "config.go", "return filepath.Clean(o)", "return filepath.Join(homeDir(), o)")
m("agent-dir-default", "config.go", 'filepath.Join(homeDir(), ".pi", "agent")', 'filepath.Join(homeDir(), ".pi")')
m("config-path", "config.go", '"extensions", extensionID, "config.json"', '"extensions", "config.json"')

# exposure.go
m("expose-keep-withheld", "exposure.go", "if isActive[n] || (b.withheld[n] && registered[n]) {", "if isActive[n] {")
m("expose-registered", "exposure.go", "if isActive[n] || (b.withheld[n] && registered[n]) {", "if isActive[n] || b.withheld[n] {")
m("expose-adopt", "exposure.go", "\t\tif !known[n] {\n\t\t\tknown[n] = true", "\t\tif known[n] {\n\t\t\tknown[n] = true")
m("expose-restored", "exposure.go", "if b.withheld[n] {\n\t\t\tr.restored", "if !b.withheld[n] {\n\t\t\tr.restored")
m("expose-changed-size", "exposure.go", "r.changed = len(b.withheld) != len(r.withheld)", "r.changed = false")
m("expose-changed-new", "exposure.go", "if !b.withheld[n] {\n\t\t\tr.changed = true", "if b.withheld[n] {\n\t\t\tr.changed = true")
m("expose-split", "exposure.go", "if isExposed(n) {\n\t\t\tr.exposed", "if !isExposed(n) {\n\t\t\tr.exposed")
m("expose-remember", "exposure.go", "b.baseline = base\n", "b.baseline = nil\n")

# extension.go
m("status-yolo", "extension.go", 'ctx.SetStatus(extensionID, "yolo")', 'ctx.SetStatus(extensionID, "YOLO")')
m("status-clear", "extension.go", '\tctx.SetStatus(extensionID, "")\n}', '\tctx.SetStatus(extensionID, "x")\n}')
m("start-issue", "extension.go", 'if st.config.Issue != "" {', 'if st.config.Issue == "" {')
m("start-permissive", "extension.go", 'if msg := detectPermissiveBashFallback(st.config.Permission); msg != "" {', 'if msg := ""; msg != "" {')
m("shutdown-status", "extension.go", 'ctx.SetStatus(extensionID, "")\n\t\treturn nil, nil\n\t})\n\te.OnEvent(sdk.EventToolCall', 'return nil, nil\n\t})\n\te.OnEvent(sdk.EventToolCall')
m("tool-call-name", "extension.go", 'name, _ := data["toolName"].(string)', 'name, _ := data["name"].(string)')
m("tool-call-input", "extension.go", 'input, _ := data["input"].(map[string]any)', "var input map[string]any")
m("tool-call-block", "extension.go", 'return map[string]any{"block": true, "reason": v.Reason}, nil', "return nil, nil")
m("agent-start-active", "extension.go", "ctx.SetActiveTools(res.exposed)", "_ = res")
m("agent-start-denied", "extension.go", "return !p.IsToolFullyDenied(n)", "return true")
m("agent-start-reload", "extension.go", "p := st.reload()\n\t\tsyncStatus(ctx, p)\n\t\t// The skills", "p := st.current()\n\t\tsyncStatus(ctx, p)\n\t\t// The skills")


# review rev-port-popular-4: bash.go (wrapper floors, chains of simple commands)
m("wrap-basename", "bash.go", "name, args := commandBasename(words[0]), words[1:]", "name, args := words[0], words[1:]")
m("wrap-eval", "bash.go", 'case name == "eval":', 'case name == "evil":')
m("wrap-shell-c", "bash.go", "case shellWrapperNames[name] && shortFlagCIndex(args) != -1:", "case shellWrapperNames[name]:")
m("wrap-dashdash", "bash.go", 'if a == "--" {\n\t\t\treturn -1', 'if false {\n\t\t\treturn -1')
m("wrap-longflag", "bash.go", '&& !strings.HasPrefix(a, "--") &&', "&&")
m("wrap-indirection", "bash.go", "case indirectionWrapperNames[name]:", "case false:")
m("wrap-flock", "bash.go", '"flock": true,', '"flockx": true,')
m("wrap-exec-cond", "bash.go", "if flags[a] {", "if flags[a+\"x\"] {")
m("wrap-fd", "bash.go", '"fd":   {"-x": true', '"fdx":  {"-x": true')
m("units-double", "bash.go", "case (c == '&' || c == '|') && i+1 < len(cmd) && cmd[i+1] == c:", "case false:")
m("units-newline", "bash.go", "case c == '|' || c == ';' || c == '\\n':", "case c == '|' || c == ';':")
m("units-trim", "bash.go", 'u := strings.Trim(cmd[start:end], " ")', "u := cmd[start:end]")
m("units-last", "bash.go", "if !cut(len(cmd)) {", "if false && !cut(len(cmd)) {")
m("decide-trim", "bash.go", "cmd := jsTrim(command)", "cmd := command")
m("unreadable-allow", "bash.go", 'if c := p.constant("bash"); c.Action != "allow" || p.yolo || cmd == "" {', 'if c := p.constant("bash"); true {')
m("unreadable-yolo", "bash.go", '|| p.yolo || cmd == "" {', '|| cmd == "" {')
m("unreadable-empty", "bash.go", '|| p.yolo || cmd == "" {', "|| p.yolo {")
m("rank-deny", "bash.go", 'case "deny":\n\t\t\tk = 3', 'case "deny":\n\t\t\tk = 0')
m("rank-first", "bash.go", "if k > rank {", "if k >= rank {")
m("floor-yolo", "bash.go", "if p.yolo {\n\t\t\t\t\tcontinue", "if false {\n\t\t\t\t\tcontinue")
m("floor", "bash.go", 'case classifyWrapperWords(words) != "":', "case false:")
m("guard", "bash.go", "case portGuardWords[commandBasename(words[0])]:", "case false:")
m("guard-ssh", "bash.go", '"unbuffer": true, "ssh": true,', '"unbuffer": true,')

# schema.go (the config schema, comments)
m("strip-block", "schema.go", "i += 2 + n + 2", "i += 2 + n")
m("strip-string", "schema.go", "case s[i] == '\"' || s[i] == '\\'':", "case s[i] == '\\'':")
m("strip-escape", "schema.go", "if c == '\\\\' {\n\t\t\t\t\tescaping = true", "if false {\n\t\t\t\t\tescaping = true")
m("schema-unrecognized", "schema.go", "s.unrecognized(extra)", "_ = extra")
m("schema-bool", "schema.go", "s.boolean(path, x)", "_ = x")
m("schema-int-inf", "schema.go", "case !ok, math.IsInf(f, 0):", "case !ok:")
m("schema-int", "schema.go", "case f != math.Trunc(f):", "case false:")
m("schema-int-min", "schema.go", "case f < 1:", "case f < 0:")
m("schema-reason-len", "schema.go", "> 500 {", "> 501 {")
m("schema-aborted", "schema.go", "if aborted {\n\t\treturn\n\t}", "if aborted && false {\n\t\treturn\n\t}")
m("schema-shape-order", "schema.go", "for _, k := range permissionShapeKeys {\n\t\tinShape[k] = true\n\t\tif _, has", "for _, k := range []string{} {\n\t\tinShape[k] = true\n\t\tif _, has")
m("schema-directional", "schema.go", "&& !directionalSurfaceKeys[k]:", "&& false:")
m("schema-empty-key", "schema.go", 'case k == "":\n\t\t\ts.at(sub(path, k), "A surface key', 'case false:\n\t\t\ts.at(sub(path, k), "A surface key')
m("schema-deny-keys", "schema.go", 'if k != "action" && k != "reason" {', 'if k != "action" && k != "reason" && false {')
m("schema-action", "schema.go", 'a != "deny" {', 'a == "" {')
m("schema-record-key", "schema.go", 'if k == "" {\n\t\t\ts.at(sub(path, k), "Invalid key in record")', 'if false {\n\t\t\ts.at(sub(path, k), "Invalid key in record")')
m("schema-required", "schema.go", "} else if required[f] {", "} else if false {")
m("schema-issues-used", "config.go", "if issues := validateUnifiedConfig(v); len(issues) > 0 {", "if issues := validateUnifiedConfig(v); false && len(issues) > 0 {")
m("config-comments", "config.go", "parseJSON([]byte(stripJSONComments(string(data))))", "parseJSON(data)")
m("shelltools-read", "config.go", "c.ShellTools = tools.order()", "_ = tools")
m("shelltools-decide", "config.go", "case p.shellTools[name]:", "case false:")
m("jsjson-range", "jsjson.go", "if errors.Is(err, strconv.ErrRange) {\n\t\t\terr = nil", "if false {\n\t\t\terr = nil")
m("schema-order", "config.go", "c.Permission = schemaPermission(perm)", "c.Permission = perm")
m("schema-proto", "schema.go", 'if !inShape[k] && k != "__proto__" {', "if !inShape[k] {")
m("schema-proto-map", "schema.go", 'if !ok || !m.has("__proto__") {', "if !ok || true {")
m("load-unreadable", "config.go", "if errors.Is(err, fs.ErrNotExist) {\n\t\t\treturn Config{}", "if err != nil || errors.Is(err, fs.ErrNotExist) {\n\t\t\treturn Config{}")

# skills.go (the skill-read gate)
m("skill-deny-filter", "skills.go", 'if state == "deny" {\n\t\t\t\tcontinue', "if false {\n\t\t\t\tcontinue")
m("skill-longest", "skills.go", "len(entries[i].baseDir) > len(best.baseDir)", "len(entries[i].baseDir) < len(best.baseDir)")
m("skill-within", "skills.go", '!strings.HasPrefix(rel, "../")', "true")
m("skill-tool", "skills.go", 'if tool != "read" || len(entries) == 0 {', "if len(entries) == 0 {")
m("skill-allow", "skills.go", 'if m == nil || m.state == "allow" {', "if m == nil {")
m("skill-at", "skills.go", 'expandHomePath(strings.TrimPrefix(t, "@"))', "expandHomePath(t)")
m("skill-home", "skills.go", 't = expandHomePath(strings.TrimPrefix(t, "@"))', 't = strings.TrimPrefix(t, "@")')
m("skill-quote", "skills.go", 'wrappingQuote.ReplaceAllString(jsTrim(value), "")', "jsTrim(value)")
m("skill-xml", "skills.go", 'return strings.ReplaceAll(xmlEntities.Replace(s), "&amp;", "&")', "return s")
m("skill-desc-required", "skills.go", "if name == nil || description == nil || location == nil {", "if name == nil || location == nil {")
m("skill-empty-name", "skills.go", 'if e.name == "" || e.location == "" {', 'if e.location == "" {')
m("skill-prompt-list", "skills.go", 'return strings.Join(parts, "\\n")', 'return ""')
m("skill-reset", "extension.go", "st.skills = nil\n", "\n")
m("skill-gate", "extension.go", "v = skillRead(name, input, st.skills, st.cwd)", "_ = skillRead")
m("skill-cwd", "extension.go", "st.skills, st.cwd = skills, ctx.Cwd()", 'st.skills, st.cwd = skills, "/"')

bad = False
for x in M:
    text = open(os.path.join(root, x["file"])).read()
    n = text.count(x["find"])
    if n != 1:
        print("find occurs", n, "times:", x["name"], file=sys.stderr)
        bad = True
if bad:
    sys.exit(1)
json.dump(M, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "w"), indent=1, ensure_ascii=False)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "a").write("\n")
print(len(M), "mutations")
