#!/usr/bin/env python3
"""Generates port/mutations.json: one deliberate defect per behavior. Each `find` must occur exactly once in its file (checked
here), so a mutation never silently applies to the wrong place."""
import json, os, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "extensions", "pi-goal-x")
M = []


def m(name, file, find, replace):
    M.append({"name": name, "file": file, "find": find, "replace": replace})


# record.go
m("safeid-astral", "record.go", 'b.WriteString("__")', 'b.WriteString("_")')
m("safeid-empty", "record.go", 'return "goal"\n\t}\n\treturn s', 'return "_"\n\t}\n\treturn s')
m("usage-floor", "record.go", "return math.Max(0, math.Floor(f))", "return math.Max(0, math.Round(f))")
m("normalize-trim", "record.go", "obj = jsTrim(obj)\n\tif obj", "if obj")
m("normalize-autocontinue-default", "record.go", "auto := true\n\tif b, ok", "auto := false\n\tif b, ok")
m("normalize-status-blocked", "record.go", '"budget_limited": true, "blocked": true}', '"budget_limited": true}')
m("task-status-skipped", "record.go", 's == "complete" || s == "skipped" {', 's == "complete" {')
m("task-empty-title", "record.go", 'if id == "" || title == "" {', 'if id == "" {')
m("tasklist-empty", "record.go", "if len(tasks) == 0 {\n\t\treturn nil\n\t}\n\tl := newObject()", "if len(tasks) < 0 {\n\t\treturn nil\n\t}\n\tl := newObject()")
m("tokenbudget-zero", "record.go", "isSafeInteger(f) && f >= 1 {", "isSafeInteger(f) && f >= 0 {")
m("stopreason-user", "record.go", 's == "agent" || s == "user" {', 's == "agent" {')
m("current-task-pending", "record.go", 'return s == "pending"', 'return s == "pending" || true')
m("focus-reason-default", "record.go", 'e := &focusEntry{reason: "selected"}', 'e := &focusEntry{reason: "created"}')
m("focus-id-safe", "record.go", "s := safeIdPart(id)\n\t\te.goalID = &s", "s := id\n\t\te.goalID = &s")
m("clone-tasks-deep", "record.go", 'n.set("tasks", tasks)\n\t\tc.set("taskList", n)', '_, _ = n, tasks\n\t\tc.set("taskList", tl)')
m("clone-usage-deep", "record.go", 'c.set("usage", u.clone())', 'c.set("usage", u)')
m("scheduler-phase-interrupted", "record.go", '"running", "interrupted") {', '"running") {')
m("scheduler-invalid-used", "record.go", 's.set("used", 9007199254740991.0)', 's.set("used", 0.0)')
m("scheduler-next-action", "record.go", 'delete(d.vals, "nextAction")\n\t\t\td.keys = removeKey(d.keys, "nextAction")', "_ = d.keys")
m("scheduler-text-limit", "record.go", "utf16Len(s) <= 2000", "utf16Len(s) < 2000")
m("scheduler-ready-decision", "record.go", 'if phase == "ready" && kind != "ready" {', 'if phase == "ready" && kind == "" {')
m("scheduler-waiting-wait", "record.go", 'if phase == "waiting" && (!(s.has("wait")', 'if phase == "waiting" && false && (!(s.has("wait")')
m("scheduler-claimed-dispatch", "record.go", 'if (phase == "claimed" || phase == "running") &&', 'if (phase == "claimed") &&')
m("scheduler-wait-interval", "record.go", "f < 1000 ||", "f < 100 ||")
m("scheduler-version", "record.go", "if ver != 1 ||", "if ver > 1 ||")
m("scheduler-decision-purpose", "record.go", '"ready", "repair", "kickoff", "recovery")) {', '"ready", "repair", "kickoff")) {')
m("scheduler-dispatch-kind", "record.go", '!inList(kind, "ready", "check", "wake", "repair", "kickoff", "recovery") {', '!inList(kind, "ready", "check", "wake", "repair", "kickoff") {')
m("new-scheduler-owner", "record.go", 's.set("owner", owner)', 's.set("owner", "x")')
# format.go
m("truncate-cut", "format.go", 'utf16Prefix(one, max-3) + "..."', 'utf16Prefix(one, max-2) + "..."')
m("truncate-limit", "format.go", "if utf16Len(one) > max {", "if utf16Len(one) >= max {")
m("title-banner", "format.go", "if titleBanner.MatchString(jsFoldSafe(line)) {", "if false {")
m("title-section", "format.go", "if titleSection.MatchString(jsFoldSafe(line)) {", "if false {")
m("title-fallback", "format.go", "return truncateText(objective, 120)\n}", "return objective\n}")
m("token-billion", "format.go", "case f >= 1e9:", "case f > 1e9:")
m("token-trim-zero", "format.go", 'return strings.TrimSuffix(s, ".0") }', "return s }")
m("token-grouping", "format.go", "(len(s)-i)%3 == 0 {", "(len(s)-i)%3 == 1 {")
m("token-negative", "format.go", "safe = 0\n\t}\n\tn := int64(safe)", "safe = 1\n\t}\n\tn := int64(safe)")
m("token-million-digits", "format.go", "if f >= 1e7 {\n\t\t\td = 0", "if f >= 1e8 {\n\t\t\td = 0")
m("duration-hours", "format.go", '"%dh%02dm%02ds"', '"%dh%dm%02ds"')
m("duration-minutes", "format.go", '"%dm%02ds"', '"%dm%ds"')
m("status-running", "format.go", 'case status == "active" && gflag(g, "autoContinue"):', 'case status == "active":')
m("status-agent", "format.go", 'gstr(g, "stopReason") == "agent":', 'gstr(g, "stopReason") != "agent":')
m("status-sisyphus", "format.go", 'prefix = "sisyphus "', 'prefix = ""')
m("status-budget", "format.go", 'return prefix + "budget limited"', 'return prefix + "budget_limited"')
m("oneline-tail", "format.go", "if tokens > 0 {\n\t\ttail =", "if tokens > 1000 {\n\t\ttail =")
m("tasks-skipped", "format.go", "if c.skipped > 0 {", "if c.skipped > 1 {")
m("tasks-none", "format.go", 'return "No tasks"', 'return "no tasks"')
m("detailed-empty", "format.go", '"No goal is set. Use /goal <objective> or /sisyphus <objective> to start immediately."\n\t}\n\ttokens', '"No goal."\n\t}\n\ttokens')
m("open-sort-id", "format.go", 'gstr(out[j], "id")) < 0', 'gstr(out[j], "id")) > 0')
m("open-sort-created", "format.go", "return c < 0\n\t\t}", "return c > 0\n\t\t}")
m("other-open-focused", "format.go", 'gstr(g, "status") != "complete" && (focused == nil || gstr(g, "id") != *focused) {', 'gstr(g, "status") != "complete" {')
m("label-marker", "format.go", 'marker = "*"\n\t}\n\tmode := "goal"\n\tif gflag(g, "sisyphus") {\n\t\tmode = "sisyphus"\n\t}\n\tpath :=', 'marker = "+"\n\t}\n\tmode := "goal"\n\tif gflag(g, "sisyphus") {\n\t\tmode = "sisyphus"\n\t}\n\tpath :=')
m("list-usage", "format.go", "tokens > 0 || seconds > 0 {", "tokens > 0 && seconds > 0 {")
m("list-empty", "format.go", '"No open goals. Use /goal <objective> or /sisyphus <objective> to start immediately."', '"No open goals."')
m("unfocused-plural", "format.go", 'if n == 1 {\n\t\ts = ""', 'if n == 2 {\n\t\ts = ""')
m("clear-message", "format.go", 'return "Goal cleared and archived."', 'return "Goal cleared."')
m("notify-icon", "format.go", 'icon, mode = "◆", "Sisyphus"', 'icon, mode = "●", "Sisyphus"')
m("notify-drive", "format.go", 'drive := "manual mode"\n\tif autoContinue {\n\t\tdrive = "auto-continue on"', 'drive := "auto-continue on"\n\tif autoContinue {\n\t\tdrive = "manual mode"')
m("notify-title-limit", "format.go", "truncateText(displayObjectiveTitle(objective), 92)", "truncateText(displayObjectiveTitle(objective), 90)")
m("contract-cr", "format.go", 'for _, line := range strings.Split(strings.ReplaceAll(objective, "\\r", ""), "\\n") {\n\t\tif m := contractRE', 'for _, line := range strings.Split(objective, "\\n") {\n\t\tif m := contractRE')
m("contract-last-wins", "format.go", "contract = jsTrim(m[1])\n", 'if contract == "" {\n\t\t\t\tcontract = jsTrim(m[1])\n\t\t\t}\n')
m("sisyphus-digits", "format.go", "(?i)\\b\\d{1,2}", "(?i)\\b\\d{2}")
m("selector-truncate", "format.go", "displayObjectiveTitle(gstr(g, \"objective\")), 72)", "displayObjectiveTitle(gstr(g, \"objective\")), 60)")
# storage.go
m("path-escape", "storage.go", 'if inside == ".." || strings.HasPrefix(inside, ".."+string(filepath.Separator)) || filepath.IsAbs(inside) {', 'if inside == ".." {')
m("safe-parent", "storage.go", "if normalizeRelPath(path.Dir(norm)) != normalizeRelPath(rootRel) {", "if false {")
m("active-name", "storage.go", "`^active_goal_.*\\.md$`)\n\tarchivedNameRE", "`^active_goal_.*`)\n\tarchivedNameRE")
m("archived-name", "storage.go", "`^goal_.*\\.md$`)", "`^goal_.*`)")
m("active-path-time", "storage.go", 'timestampForFile(gstr(g, "createdAt")), safeIdPart(gstr(g, "id")))\n}\n\nfunc makeArchivedGoalPath', 'timestampForFile(gstr(g, "updatedAt")), safeIdPart(gstr(g, "id")))\n}\n\nfunc makeArchivedGoalPath')
m("archived-path-time", "storage.go", 'timestampForFile(gstr(g, "updatedAt")), safeIdPart(gstr(g, "id")))\n}\n\nfunc activePathForGoal', 'timestampForFile(gstr(g, "createdAt")), safeIdPart(gstr(g, "id")))\n}\n\nfunc activePathForGoal')
m("timestamp-hundredths", "storage.go", "t.Nanosecond()/1e6/10)", "t.Nanosecond()/1e7*0+t.Nanosecond()/1e6)")
m("timestamp-month", "storage.go", "int(t.Month()), t.Day()", "int(t.Month())-1, t.Day()")
m("task-evidence", "storage.go", '"evidence: "+', '"evidence:"+')
m("task-skip-reason", "storage.go", '"skipped: "+', '"skip: "+')
m("task-contract", "storage.go", '"contract: "+', '"contract:"+')
m("task-pending-only", "storage.go", 'if status == "pending" && truthy(t.vals["verificationContract"]) {', 'if status != "complete" && truthy(t.vals["verificationContract"]) {')
m("task-box-skipped", "storage.go", 'return "~"', 'return "x"')
m("task-block", "storage.go", "<!-- blockCompletion: %v -->", "<!-- blockcompletion: %v -->")
m("contract-line-trim", "storage.go", 'c := jsTrim(strOrEmpty(g, "verificationContract")); c != ""', 'c := strOrEmpty(g, "verificationContract"); c != ""')
m("pause-reason-line", "storage.go", '"- Agent pause reason: "', '"- Pause reason: "')
m("suggest-line", "storage.go", '"- Agent suggests: "', '"- Suggests: "')
m("serialize-version", "storage.go", 'head.set("version", 3.0)', 'head.set("version", 2.0)')
m("json-escape", "storage.go", "} else if c == '\\\\' {", "} else if c == '/' {")
m("json-string", "storage.go", "} else if c == '\"' {\n\t\t\t\tinString = false", "} else if c == '\\'' {\n\t\t\t\tinString = false")
m("body-edit", "storage.go", 'merged.set("objective", obj)', "_ = obj")
m("body-progress", "storage.go", 'if jsTrim(lines[i]) == "## Progress" {', 'if jsTrim(lines[i]) == "## Progress " {')
m("write-updated-at", "storage.go", 'n.set("activePath", active)\n\tn.set("updatedAt", nowIso())', 'n.set("activePath", active)')
m("archive-removes-active", "storage.go", 'delete(next.vals, "activePath")\n\tnext.keys = removeKey(next.keys, "activePath")', "_ = next.keys")
m("archive-unlink", "storage.go", "_ = s.safeUnlink(goalsDir, p)", "_ = p")
m("scan-complete", "storage.go", 'if g == nil || gstr(g, "status") == "complete" {', "if g == nil {")
m("scan-activepath", "storage.go", 'n.set("activePath", rel)\n\t\tout = append', 'out = append')
m("snapshot-names", "storage.go", "if !remaining[name] {", "if false {")
m("snapshot-leftover", "storage.go", "return len(remaining) == 0", "return true")
m("snapshot-complete", "storage.go", 'if !ok || gstr(g, "status") == "complete" {', "if !ok {")
m("snapshot-legacy", "storage.go", "return tryParseSnapshot(filepath.Join(s.root(), snapshotLegacy))", "return nil")
m("snapshot-mtime", "storage.go", "match := sn.dirMtime == mtimeMs(fi)", "match := true")
m("snapshot-update", "storage.go", "\t\tdelete(poolCache, s.root())\n\t\t_ = rootDir", "\t\t_ = rootDir")
m("unlink-invalidates", "storage.go", "\t\ts.invalidateDir()\n\t\tif rootRel == goalsDir {", "\t\tif rootRel == goalsDir {")
m("ledger-newline", "storage.go", '\t\tb.WriteString("\\n")\n\t}\n\tf, err := os.OpenFile(file, os.O_WRONLY|os.O_APPEND', '\t}\n\tf, err := os.OpenFile(file, os.O_WRONLY|os.O_APPEND')
m("lock-attempts", "storage.go", "attempts, retryMs = 8, 1", "attempts, retryMs = 0, 1")
# core.go
m("focus-takes-ledger", "core.go", 'if recordLedger && c.focused != nil {', 'if false && c.focused != nil {')
m("unfocus-ledger", "core.go", '} else if recordLedger && prev != nil {', '} else if prev != nil {')
m("resolve-legacy-complete", "core.go", 'if legacy != nil && gstr(legacy, "status") != "complete" {\n\t\tid := gstr(legacy, "id")', 'if legacy != nil {\n\t\tid := gstr(legacy, "id")')
m("resolve-entry-null", "core.go", "\tif entry != nil {\n\t\treturn nil\n\t}\n\tif legacy", "\tif legacy")
m("resolve-autoselect", "core.go", "if autoSelect {\n\t\tif open", "if !autoSelect {\n\t\tif open")
m("load-focus-entry-migrated", "core.go", 'reason = "migrated"', 'reason = "selected"')
m("load-focus-entry-written", "core.go", "if entry == nil && c.focused != nil {", "if entry == nil && c.focused != nil && false {")
m("load-legacy-sanitize", "core.go", "legacy = sanitizeGoalPaths(c.st, c.st.mergeGoalPromptFromDisk(legacy))", "legacy = c.st.mergeGoalPromptFromDisk(legacy)")
m("reconcile-lost-notify-ui", "core.go", "c.assignFocused(nil)\n\t\tc.updateUI()\n\t\treturn false", "c.assignFocused(nil)\n\t\treturn false")
m("apply-revision", "core.go", "diskRev != captured {", "diskRev < captured {")
m("apply-revision-bump", "core.go", 'mutated.set("revision", captured+1)', 'mutated.set("revision", captured)')
m("apply-fresh-missing", "core.go", "if fresh == nil {", "if fresh == nil && false {")
m("apply-commit", "core.go", "if !spec.noCommitFocused {", "if spec.noCommitFocused {")
m("apply-ledger", "core.go", "if spec.ledger != nil {\n\t\tc.appendEvents(spec.ledger(written)...)", "if spec.ledger != nil && false {\n\t\tc.appendEvents(spec.ledger(written)...)")
m("scheduler-stop-notice", "core.go", 'func (c *core) schedulerSafe(fn func() error) {\n\tif err := fn(); err != nil {\n\t\tc.h.Notify("Goal scheduling stopped: "+err.Error(), "warning")', 'func (c *core) schedulerSafe(fn func() error) {\n\tif err := fn(); err != nil {\n\t\tc.h.Notify("Goal scheduling stopped", "warning")')
m("takeover-owner", "core.go", 'owner, _ := s.str("owner"); owner != c.h.SessionID() {\n\t\treturn\n\t}', 'owner, _ := s.str("owner"); owner == "" {\n\t\treturn\n\t}')
m("takeover-generation", "core.go", 's.set("generation", newUUID())\n\t\t\ts.set("phase", "idle")', 's.set("phase", "idle")')
m("takeover-repair", "core.go", 's.set("repairUsed", false)\n\t\t})', "})")
m("takeover-on-change", "core.go", "if (prev == nil) != (id == nil) || (prev != nil && *prev != *id) {\n\t\tc.takeover()", "if false {\n\t\tc.takeover()")
m("allowance-text", "core.go", '"Automatic continuation disabled by maxAutonomousRuns=0. Change the setting in /goal-settings, then use /goal-resume."', '"Automatic continuation disabled."')
m("kickoff-limit", "core.go", "if limit != nil && *limit == 0 {\n\t\t\tif err := c.schedulerUpdate(func(*jsObject) {}); err != nil {", "if limit != nil && *limit <= 1 {\n\t\t\tif err := c.schedulerUpdate(func(*jsObject) {}); err != nil {")
m("kickoff-noop-write", "core.go", "if err := c.schedulerUpdate(func(*jsObject) {}); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n\t\t\tc.h.Notify(allowanceReason(limit), \"info\")", 'c.h.Notify(allowanceReason(limit), "info")')
m("kickoff-ready-phase", "core.go", 's.set("phase", "ready")\n\t\t\td := newObject()', 's.set("phase", "idle")\n\t\t\td := newObject()')
m("kickoff-ready-purpose", "core.go", 'd.set("purpose", "kickoff")', 'd.set("purpose", "ready")')
m("replace-scheduler", "core.go", 'goal.set("scheduler", newGoalScheduler(c.h.SessionID()))', "_ = goal")
m("replace-contract", "core.go", 'if contract != "" {\n\t\tgoal.set("verificationContract", contract)', 'if contract == "" {\n\t\tgoal.set("verificationContract", contract)')
m("replace-ledger-auto", "core.go", '"sisyphus", sisyphus, "autoContinue", true, "at"', '"sisyphus", sisyphus, "autoContinue", false, "at"')
m("replace-focus-entry", "core.go", "if res.focusChanged {\n\t\tc.appendFocusEntry(strp(gstr(res.goal, \"id\")), \"created\")", "if !res.focusChanged {\n\t\tc.appendFocusEntry(strp(gstr(res.goal, \"id\")), \"created\")")
m("replace-budget", "core.go", '+"\\nBudget: none"', '+"\\nBudget: unlimited"')
m("create-focus-changed", "core.go", "focusChanged: prev == nil || gstr(prev, \"id\") != gstr(written, \"id\")", "focusChanged: prev == nil")
m("pause-autocontinue", "core.go", 'next.set("autoContinue", false)', 'next.set("autoContinue", true)')
m("pause-reason-cleared", "core.go", 'next.set("pauseReason", undef{})\n\tnext.set("pauseSuggestedAction", undef{})', 'next.set("pauseSuggestedAction", undef{})')
m("pause-stop-reason", "core.go", 'n.set("stopReason", "user")\n\t\tn.set("updatedAt", nowIso())', 'n.set("stopReason", "agent")\n\t\tn.set("updatedAt", nowIso())')
m("pause-status", "core.go", 'n.set("status", "paused")\n\t\tn.set("stopReason", "user")', 'n.set("status", "blocked")\n\t\tn.set("stopReason", "user")')
m("pause-ledger-reason", "core.go", '"reason", "user", "suggestedAction"', '"reason", "agent", "suggestedAction"')
m("pause-notify", "core.go", 'c.h.Notify("Goal paused.", "info")', 'c.h.Notify("Goal paused", "info")')
m("pause-only-active", "core.go", 'if g == nil || gstr(g, "status") != "active" {\n\t\treturn\n\t}\n\tnext', 'if g == nil {\n\t\treturn\n\t}\n\tnext')
m("pause-ui", "core.go", "if res != nil {\n\t\tc.updateUI()\n\t}", "_ = res")
m("archive-status", "core.go", 'status := "paused"\n\t\tif gstr(g, "status") == "complete" {', 'status := "active"\n\t\tif gstr(g, "status") == "complete" {')
m("archive-stop", "core.go", 'n.set("stopReason", reason)\n\t\treturn n, nil', 'return n, nil')
m("choose-single", "core.go", "if len(open) == 1 {\n\t\tc.setFocusedGoalID", "if len(open) == 2 {\n\t\tc.setFocusedGoalID")
m("choose-headless", "core.go", "if !c.h.HasUI() {\n\t\tc.h.Notify(buildUnfocusedOpenGoalsSummary(len(open)), \"warning\")", "if false {\n\t\tc.h.Notify(buildUnfocusedOpenGoalsSummary(len(open)), \"warning\")")
m("choose-unchanged", "core.go", '"Goal focus unchanged."', '"Focus unchanged."')
m("direct-empty", "core.go", 'cmd := "/goal <objective>"', 'cmd := "/goal"')
m("direct-sisyphus-text", "core.go", '"/sisyphus <objective>"\n\t\t}', '"/goal <objective>"\n\t\t}')
m("direct-sisyphus-check", "core.go", "if sisyphus && !sisyphusObjectiveSufficient(raw) {", "if false {")
m("direct-contracts-setting", "core.go", "if !loadGoalSettings(c.h.Cwd()).disableContracts {", "if true {")
m("list-reconcile", "core.go", "func (c *core) list() {\n\tc.reconcileFocused()", "func (c *core) list() {")
m("pause-none-open", "core.go", 'c.h.Notify("No goal is set.", "warning")\n\t\t\treturn', 'c.h.Notify("No goal set.", "warning")\n\t\t\treturn')
m("pause-paused-text", "core.go", '"Goal is already paused. Use /goal-resume to continue."', '"Goal already paused."')
m("pause-flush", "core.go", "c.flush() // the original awaits here, which lets the queued UI update run\n\t\t\tif picked == nil {", "if picked == nil {")
m("clear-headless", "core.go", 'if !c.h.HasUI() {\n\t\tc.h.Notify("Run /goal-clear', 'if false {\n\t\tc.h.Notify("Run /goal-clear')
m("clear-cancel-text", "core.go", '"Goal clear cancelled."', '"Cancelled."')
m("clear-token", "core.go", "c.focusRev != rev ||", "c.focusRev != rev && false ||")
m("clear-cleared-entry", "core.go", "if prev != nil && c.focused == nil {\n\t\tc.appendFocusEntry(nil, reason)", "if prev != nil && c.focused != nil {\n\t\tc.appendFocusEntry(nil, reason)")
m("clear-level", "core.go", 'level := "info"\n\tif archived == nil {', 'level := "warning"\n\tif archived == nil {')
m("unfocus-text", "core.go", '"Goal unfocused for this session. It remains open in .pi/goals: "', '"Goal unfocused. It remains open in .pi/goals: "')
m("unfocus-open-summary", "core.go", "if n := otherOpenGoalCount(c.goals, nil); n > 0 {", "if n := otherOpenGoalCount(c.goals, nil); n > 1 {")
m("unfocus-reconcile", "core.go", "c.reconcileFocused()\n\tcurrent = c.state()\n\tdetached", "current = c.state()\n\tdetached")
m("unfocus-abort", "core.go", "if detached != \"\" && busy {", "if detached != \"\" && !busy {")
m("persist-revision", "core.go", 'gnum(fresh, "revision") != captured {', "false {")
m("persist-bump", "core.go", 'n.set("revision", captured+1)\n\tmerged', 'n.set("revision", captured)\n\tmerged')
m("shutdown-persist", "core.go", "func (c *core) shutdown() {\n\tc.persist()", "func (c *core) shutdown() {")
m("render-unfocused", "core.go", 'fmt.Sprintf("goal: unfocused [%d open] - /goal-focus", totalOpen)', 'fmt.Sprintf("goal: unfocused [%d open]", totalOpen)')
m("render-clear", "core.go", "if g == nil && totalOpen == 0 {\n\t\tc.clearGoalWidget()", "if g == nil && totalOpen == 0 {\n\t\tc.h.SetStatus(widgetKey, \"\")")
m("clear-widget-ui", "core.go", "if c.h.HasUI() {\n\t\tc.h.SetStatus(widgetKey, \"\")\n\t\tc.h.ClearWidget(widgetKey)", "if c.h.HasUI() {\n\t\tc.h.ClearWidget(widgetKey)")
m("flush-once", "core.go", "c.uiPending = false\n\tc.renderUI()", "c.renderUI()")
m("footer-sisyphus", "core.go", 'prefix = "goal✊"', 'prefix = "goal"')
# restore and schedule
m("restore-other-owner", "core.go", 'owner != c.h.SessionID() {\n\t\t\tc.h.Notify("Goal owned by another session', 'owner == "" {\n\t\t\tc.h.Notify("Goal owned by another session')
m("restore-interrupted", "core.go", 'inList(phase, "claimed", "running", "interrupted")', 'inList(phase, "claimed", "running")')
m("restore-no-scheduler", "core.go", 'gstr(g, "status") != "active" || !gflag(g, "autoContinue") || !g.has("scheduler") {\n\t\t\treturn nil\n\t\t}\n\t\ts := g.obj("scheduler")', 'gstr(g, "status") != "active" || !gflag(g, "autoContinue") {\n\t\t\treturn nil\n\t\t}\n\t\ts := g.obj("scheduler")')
m("schedule-phase", "core.go", 'phase != "ready" && phase != "waiting" {', 'phase != "ready" {')
m("budget-reached", "core.go", "return b > 0 && tokens >= b", "return b > 0 && tokens > b")
m("budget-skipped", "core.go", "\tif budgetReached(g) {\n\t\tc.schedulerPause", "\tif false {\n\t\tc.schedulerPause")
m("allowance-used", "core.go", "if limit != nil && used >= *limit {", "if limit != nil && used > *limit {")
m("wait-deadline", "core.go", 'c.schedulerPause("Wait deadline reached.")', 'c.schedulerPause("Wait deadline.")')
m("pause-source", "core.go", '"reason", r, "source", "agent", "at", nowIso())}\n\t}})\n\tif err != nil {\n\t\tc.h.Notify("Goal scheduling stopped', '"reason", r, "source", "user", "at", nowIso())}\n\t}})\n\tif err != nil {\n\t\tc.h.Notify("Goal scheduling stopped')
m("pause-generation", "core.go", 'ns.set("generation", newUUID())', "_ = ns")
m("write-ledger-paused", "core.go", 'if gstr(w, "status") != "paused" {\n\t\t\treturn nil', 'if gstr(w, "status") != "paused" || true {\n\t\t\treturn nil')
m("load-flush", "core.go", "c.loadState()\n\tc.flush()\n\tc.restore()", "c.loadState()\n\tc.restore()")
# settings.go
m("settings-project-wins", "settings.go", "case project.maxRuns != nil:\n\t\ts.maxAutonomousRuns = project.maxRuns\n\tcase global.maxRuns != nil:\n\t\ts.maxAutonomousRuns = global.maxRuns", "case global.maxRuns != nil:\n\t\ts.maxAutonomousRuns = global.maxRuns\n\tcase project.maxRuns != nil:\n\t\ts.maxAutonomousRuns = project.maxRuns")
m("settings-env-first", "settings.go", "case envv != nil:\n\t\ts.disableContracts = *envv\n\tcase project.disableContracts != nil:\n\t\ts.disableContracts = *project.disableContracts", "case project.disableContracts != nil:\n\t\ts.disableContracts = *project.disableContracts\n\tcase envv != nil:\n\t\ts.disableContracts = *envv")
m("settings-bool-string", "settings.go", 'if x == "true" || x == "false" {\n\t\t\tb := x == "true"', 'if x == "true" || x == "false" || x == "1" {\n\t\t\tb := x == "true" || x == "1"')
m("settings-digits", "settings.go", "if s := jsTrim(t); digitsOnly.MatchString(s) {", "if s := t; digitsOnly.MatchString(s) {")
m("settings-env-file", "settings.go", 'if o := nonEmpty(getenv("PI_GOAL_SETTINGS_FILE")); o != "" {', 'if o := ""; o != "" {')
m("settings-agentdir", "settings.go", 'if o := nonEmpty(getenv("PI_CODING_AGENT_DIR")); o != "" {', 'if o := ""; o != "" {')
m("settings-autoselect", "settings.go", "l.autoSelect = asBool(o.vals[\"autoSelectSingleGoal\"])", "")
# jsjson.go
m("json-undef-skipped", "jsjson.go", "if _, u := vals[k].(undef); !u {", "if true {")
m("json-order", "jsjson.go", "return append(idx, rest...)", "return append(rest, idx...)")

# Review additions (rev-port-popular-3). The SDK adapter had no mutation and no unit test; these are killed by adapter_test.go.
m("adapter-session-id", "extension.go", "\tid, _ := h.ctx.GetSessionID()\n\treturn id", "\t_, _ = h.ctx.GetSessionID()\n\treturn \"\"")
m("adapter-rich-rpc", "extension.go", 'h.ctx.HasUI() && h.ctx.Mode() != "rpc"', "h.ctx.HasUI()")
m("adapter-rich-none", "extension.go", 'func (h sdkHost) Rich() bool            { return h.ctx.HasUI() && h.ctx.Mode() != "rpc" }', "func (h sdkHost) Rich() bool            { return false }")
m("adapter-idle-error", "extension.go", "return err != nil || idle", "return err == nil && idle")
m("adapter-idle-ignored", "extension.go", "\treturn err != nil || idle\n", "\treturn err != nil || idle || true\n")
m("adapter-confirm-yes", "extension.go", "\tok, _ := h.ctx.Confirm(t, m)\n\treturn ok", "\t_, _ = h.ctx.Confirm(t, m)\n\treturn true")
m("adapter-branch-empty", "extension.go", "\traw, err := h.ctx.SessionManager().GetBranch(nil)\n", "\traw, err := h.ctx.SessionManager().GetBranch(nil)\n\traw = nil\n")
m("adapter-no-entries", "extension.go", "_ = h.ctx.AppendEntry(t, d)", "_, _ = t, d")
m("adapter-no-shutdown", "extension.go", "a.with(ctx, func(c *core) { c.shutdown() })", "_ = ctx")
m("adapter-hasui", "extension.go", "func (h sdkHost) HasUI() bool           { return h.ctx.HasUI() }", "func (h sdkHost) HasUI() bool           { return true }")
m("adapter-no-abort", "extension.go", "func (h sdkHost) Abort() { h.ctx.Abort() }", "func (h sdkHost) Abort() {}")
# Mutants that survived every test before the review: killed by the new sessions (headless, busy, removed during confirm,
# deadline now, other storage root) and by the goal-pool-snapshot twins.
m("wait-deadline-now", "core.go", "float64(clockMs()) >= dl", "float64(clockMs()) > dl")
m("entry-root", "core.go", "if entryRoot != root {", "if false && entryRoot != root {")
m("snapshot-legacy-kept", "storage.go", "\t_ = os.Remove(filepath.Join(s.root(), snapshotLegacy))", "")
m("snapshot-mtime-recorded", "storage.go", '\thead.set("dirMtimeMs", mt)', '\thead.set("dirMtimeMs", 0.0)')
# The review's fixes: JavaScript /i, out-of-range numbers, the implicit ready at restore.
m("fold-safe", "format.go", 'strings.NewReplacer("\\u017f", "\\ufffd", "\\u212a", "\\ufffd")', 'strings.NewReplacer("\\u017f", "\\u017f")')
m("json-range", "jsjson.go", "if errors.Is(err, strconv.ErrRange) {\n\t\t\terr = nil", "if false {\n\t\t\terr = nil")
m("json-nonfinite-null", "jsjson.go", 'if math.IsNaN(x) || math.IsInf(x, 0) {\n\t\t\tb.WriteString("null")', 'if math.IsNaN(x) && false {\n\t\t\tb.WriteString("null")')
m("implicit-ready", "core.go", 'phase == "ready" && repairPending(s) && !c.strict(s) {', 'phase == "ready" && repairPending(s) && false {')
m("implicit-ready-strict", "core.go", "return loadGoalSettings(c.h.Cwd()).strictExecutionContract || (s.has", "return false || (s.has")
m("implicit-ready-purpose", "core.go", 'return kind == "ready" && purpose == "repair"', 'return kind == "ready" && (purpose == "repair" || true)')
m("settings-strict", "settings.go", 'l.strict = asBool(o.vals["strictExecutionContract"])', "")

bad = 0
for x in M:
    src = open(os.path.join(root, x["file"])).read()
    n = src.count(x["find"])
    if n != 1:
        print(f'{x["name"]}: find occurs {n} times in {x["file"]}', file=sys.stderr)
        bad += 1
if bad:
    sys.exit(1)
json.dump(M, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "w"), indent=1, ensure_ascii=False)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "a").write("\n")
print(len(M), "mutations")
