package warden

import (
	"encoding/json"
	"os"
	"strings"
	"testing"
)

// The differential corpus: 1,600+ commands run through the ORIGINAL pi-warden (generated by
// port/gen-corpus.ts against the pinned oracle) and through this port. The pattern pass, the read-only
// shortcut, the visible-effect check, the data-text stripping and the redaction must agree on every one.
// Go's RE2 has no lookahead, so the hand-written helpers are exactly what this guards.

type corpusItem struct {
	Command  string   `json:"command"`
	Patterns []string `json:"patterns"`
	ReadOnly bool     `json:"readOnly"`
	Visible  bool     `json:"visible"`
	Stripped struct {
		Text     string `json:"text"`
		Stripped bool   `json:"stripped"`
	} `json:"stripped"`
	Redacted string `json:"redacted"`
}

// sqlTargetIDs are the hits of upstream's SQL target classification (loopback and hosted databases), which
// this port defers (PORT.md); the plain sql-* rules still apply.
var sqlTargetIDs = map[string]bool{"sql-delete-local": true, "sql-hosted": true, "sql-hosted-write": true}

func TestDifferentialAgainstThePinnedOriginal(t *testing.T) {
	raw, err := os.ReadFile("testdata/diff_corpus.json")
	if err != nil {
		t.Fatal(err)
	}
	var items []corpusItem
	if err := json.Unmarshal(raw, &items); err != nil {
		t.Fatal(err)
	}
	if len(items) < 1000 {
		t.Fatalf("corpus too small: %d", len(items))
	}
	bad := 0
	report := func(kind string, it corpusItem, got, want any) {
		bad++
		if bad <= 40 {
			t.Errorf("%s differs for %q\n  port:     %v\n  original: %v", kind, it.Command, got, want)
		}
	}
	skippedSQL := 0
	for _, it := range items {
		var want []string
		sqlTouched := false
		for _, p := range it.Patterns {
			id := strings.SplitN(p, "|", 2)[0]
			if sqlTargetIDs[id] {
				sqlTouched = true
				continue
			}
			want = append(want, p)
		}
		var got []string
		for _, h := range MatchPatterns("bash", map[string]any{"command": it.Command}, "", &PatternOptions{}) {
			got = append(got, h.ID+"|"+string(h.Severity)+"|"+h.Label)
		}
		// Upstream drops sql-delete when every DELETE targets a loopback database; that is the deferred classification.
		if sqlTouched || strings.Contains(strings.ToLower(it.Command), "delete from") {
			if strings.Join(without(got, "sql-delete"), "\n") == strings.Join(without(want, "sql-delete"), "\n") {
				skippedSQL++
				continue
			}
		}
		if strings.Join(got, "\n") != strings.Join(want, "\n") {
			report("patterns", it, got, want)
		}
		if ro := IsReadOnlyCommand(it.Command); ro != it.ReadOnly {
			report("read-only", it, ro, it.ReadOnly)
		}
		if v := IsVisibleCommand(it.Command); v != it.Visible {
			report("visible", it, v, it.Visible)
		}
		if s := StripDataText(it.Command); s.Text != it.Stripped.Text || s.Stripped != it.Stripped.Stripped {
			report("stripDataText", it, s, it.Stripped)
		}
		if r := Redact(it.Command); r != it.Redacted {
			report("redact", it, r, it.Redacted)
		}
	}
	t.Logf("%d commands compared (%d SQL-target cases compared without the deferred classification)", len(items), skippedSQL)
	if bad > 0 {
		t.Fatalf("%d differences", bad)
	}
}

func without(list []string, id string) []string {
	var out []string
	for _, s := range list {
		if !strings.HasPrefix(s, id+"|") {
			out = append(out, s)
		}
	}
	return out
}
