package account

import (
	"strings"
	"testing"
	"time"
)

var now = time.Unix(1700000000, 0)

const netscape = `# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	TRUE	4102444800	SAPISID	SAPISIDVALUE123
#HttpOnly_.youtube.com	TRUE	/	TRUE	4102444800	__Secure-3PAPISID	THREEPVALUE
.youtube.com	TRUE	/	TRUE	4102444800	__Secure-1PAPISID	ONEPVALUE
.google.com	TRUE	/	TRUE	4102444800	SID	GOOGLESID
.example.com	TRUE	/	TRUE	4102444800	session	NOTMINE
.youtube.com	TRUE	/	TRUE	1000	EXPIRED	OLD
.youtube.com	TRUE	/	TRUE	0	SESSIONONLY	KEEP
# Netscape HTTP Cookie File
`

func TestOnlyYouTubeCookiesAreKeptAndExpiredOnesAreNot(t *testing.T) {
	jar, err := ParseNetscape(strings.NewReader(netscape), now)
	if err != nil {
		t.Fatal(err)
	}
	names := map[string]bool{}
	for _, c := range jar {
		names[c.Name] = true
		if strings.Contains(c.Value, "NOTMINE") {
			t.Error("a cookie of another site was kept")
		}
	}
	for _, want := range []string{"SAPISID", "__Secure-3PAPISID", "__Secure-1PAPISID", "SESSIONONLY"} {
		if !names[want] {
			t.Errorf("lacks %s: %v", want, names)
		}
	}
	if names["session"] || names["EXPIRED"] || names["SID"] { // SID is google.com's: not sent to music.youtube.com
		t.Errorf("kept %v", names)
	}
}

// 1d8ef72e... is sha1("1700000000 SAPISIDVALUE123 https://music.youtube.com") from sha1sum, not from this package.
func TestTheAuthorizationHeaderIsSAPISIDHASHOfTimeCookieAndOrigin(t *testing.T) {
	jar, _ := ParseNetscape(strings.NewReader(netscape), now)
	h, ok := jar.Authorization("https://music.youtube.com", now)
	if !ok {
		t.Fatal("no header")
	}
	if !strings.HasPrefix(h, "SAPISIDHASH 1700000000_1d8ef72e6dfbb1696da7299239fca32ded5f049f") {
		t.Errorf("header %q", h)
	}
	for _, want := range []string{" SAPISID1PHASH 1700000000_", " SAPISID3PHASH 1700000000_"} {
		if !strings.Contains(h, want) {
			t.Errorf("lacks %q: %q", want, h)
		}
	}
}

func TestWithoutSAPISIDThereIsNoHeaderAndTheJarSaysItIsNotSignedIn(t *testing.T) {
	jar, _ := ParseNetscape(strings.NewReader(".youtube.com\tTRUE\t/\tTRUE\t0\tSID\tx\n"), now)
	if _, ok := jar.Authorization("https://music.youtube.com", now); ok {
		t.Error("a header without SAPISID")
	}
	if jar.SignedIn() {
		t.Error("signed in without SAPISID")
	}
}

func TestACookieHeaderHasNameValuePairsAndTheJarNeverPrintsValues(t *testing.T) {
	jar, _ := ParseNetscape(strings.NewReader(netscape), now)
	h := jar.Header()
	if !strings.Contains(h, "SAPISID=SAPISIDVALUE123") || strings.Contains(h, "NOTMINE") {
		t.Errorf("header %q", h)
	}
	if s := jar.String(); strings.Contains(s, "VALUE") || strings.Contains(s, "GOOGLESID") {
		t.Errorf("String() shows values: %q", s)
	}
}

// A browser holds a SAPISID for google.com as well as for youtube.com, with another value. The browser sends only the
// youtube.com ones to music.youtube.com, and the signature must be made from the one the request carries: a google.com cookie
// listed first must neither sign the request nor travel with it.
func TestOnlyCookiesThatTheBrowserWouldSendToYouTubeMusicAreKept(t *testing.T) {
	text := ".google.com\tTRUE\t/\tTRUE\t4102444800\tSAPISID\tGOOGLESAPISID\n" +
		".google.com\tTRUE\t/\tTRUE\t4102444800\tSID\tGOOGLESID\n" +
		"accounts.google.com\tFALSE\t/\tTRUE\t4102444800\tLSID\tACCOUNTSLSID\n" +
		"www.youtube.com\tFALSE\t/\tTRUE\t4102444800\tWWWONLY\tWWWVALUE\n" +
		".youtube.com\tTRUE\t/\tTRUE\t4102444800\tSAPISID\tSAPISIDVALUE123\n" +
		"music.youtube.com\tFALSE\t/\tTRUE\t4102444800\tMUSICONLY\tMUSICVALUE\n"
	jar, err := ParseNetscape(strings.NewReader(text), now)
	if err != nil {
		t.Fatal(err)
	}
	h, _ := jar.Authorization("https://music.youtube.com", now)
	if !strings.HasPrefix(h, "SAPISIDHASH 1700000000_1d8ef72e6dfbb1696da7299239fca32ded5f049f") {
		t.Errorf("signed with another cookie: %q", h)
	}
	header := jar.Header()
	for _, leak := range []string{"GOOGLE", "ACCOUNTS", "WWWVALUE"} {
		if strings.Contains(header, leak) {
			t.Errorf("the Cookie header carries a cookie of another host (%s): %q", leak, header)
		}
	}
	if !strings.Contains(header, "MUSICONLY=MUSICVALUE") || !strings.Contains(header, "SAPISID=SAPISIDVALUE123") {
		t.Errorf("header %q", header)
	}
}
