#!/usr/bin/env python3
"""Generates extensions/ahp/internal/wire/dispatchable.go from the pinned AHP spec.

usage: gen-dispatchable.py <agent-host-protocol checkout at the pinned commit>
Source of truth: types/action-origin.generated.ts (IS_CLIENT_DISPATCHABLE), whose keys are
ActionType members; member -> wire string comes from the vendored Go client's ahptypes constants.
"""
import re, sys
spec = sys.argv[1]
ts = open(f"{spec}/types/action-origin.generated.ts").read()
block = ts[ts.index("IS_CLIENT_DISPATCHABLE"):]
block = block[:block.index("};")]
members = re.findall(r"\[ActionType\.(\w+)\]:\s*(true|false)", block)
go = open(f"{spec}/clients/go/ahptypes/actions.generated.go").read()
consts = dict(re.findall(r"ActionType(\w+)\s+ActionType\s*=\s*\"([^\"]+)\"", go))
out = []
for name, flag in members:
    if name not in consts:
        raise SystemExit(f"no Go constant for ActionType.{name}")
    out.append((consts[name], flag == "true"))
out.sort()
print("// Code generated by proof/tools/gen-dispatchable.py from microsoft/agent-host-protocol")
print("// types/action-origin.generated.ts (IS_CLIENT_DISPATCHABLE) at the pinned commit; DO NOT EDIT.")
print()
print("package wire")
print()
print("var clientDispatchable = map[string]bool{")
for t, f in out:
    print(f'\t"{t}": {"true" if f else "false"},')
print("}")
