#!/usr/bin/env python3
"""Generates port/mutations.json: one deliberate defect per contract row. Each `find` must occur exactly
once in its file (checked here), so a mutation never silently applies to the wrong place."""
import json, os, sys

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "extensions", "powerline-footer")
M = []


def m(name, file, find, replace):
    M.append({"name": name, "file": file, "find": find, "replace": replace})


# segments.go
m("tokens-1k-boundary", "segments.go", 'case n < 1000:\n\t\treturn jsNumber(n)', 'case n <= 1000:\n\t\treturn jsNumber(n)')
m("tokens-10k-fixed", "segments.go", 'case n < 10000:\n\t\treturn jsToFixed(n/1000, 1) + "k"', 'case n < 10000:\n\t\treturn jsNumber(jsRound(n/1000)) + "k"')
m("tokens-round-to-floor", "segments.go", 'return jsNumber(jsRound(n/1000)) + "k"\n\tcase n < 10000000', 'return jsNumber(math.Floor(n/1000)) + "k"\n\tcase n < 10000000')
m("tokens-million-fixed", "segments.go", 'case n < 10000000:\n\t\treturn jsToFixed(n/1000000, 1) + "M"', 'case n < 10000000:\n\t\treturn jsNumber(jsRound(n/1000000)) + "M"')
m("duration-hours", "segments.go", 'return jsNumber(hours) + "h" + jsNumber(math.Mod(minutes, 60)) + "m"', 'return jsNumber(hours) + "h" + jsNumber(minutes) + "m"')
m("duration-minutes", "segments.go", 'return jsNumber(minutes) + "m" + jsNumber(math.Mod(seconds, 60)) + "s"', 'return jsNumber(minutes) + "m" + jsNumber(seconds) + "s"')
m("model-claude-prefix", "segments.go", 'strings.CutPrefix(name, "Claude ")', 'strings.CutPrefix(name, "Claude")')
m("model-qualified-prefix-check", "segments.go", '!strings.HasPrefix(ctx.Model.ID, provider+"/")', 'true')
m("model-thinking-needs-reasoning", "segments.go", 'ctx.Model != nil && ctx.Model.Reasoning {\n\t\tlevel', 'ctx.Model != nil {\n\t\tlevel')
m("model-no-model-text", "segments.go", 'name := "no-model"', 'name := "none"')
m("path-home-tilde", "segments.go", 'pwd = "~" + pwd[len(home):]', 'pwd = pwd[len(home):]')
m("path-work-prefix", "segments.go", 'pwd = pwd[6:]', 'pwd = pwd[5:]')
m("path-abbrev-default-max", "segments.go", 'maxLen := 40', 'maxLen := 30')
m("path-abbrev-ellipsis", "segments.go", 'pwd = "…" + utf16Tail(pwd, maxLen-1)', 'pwd = "…" + utf16Tail(pwd, maxLen)')
m("path-abbrev-only", "segments.go", 'if mode == "abbreviated" {', 'if mode != "basename" {')
m("git-dirty-color", "segments.go", 'branchColor = "gitDirty"', 'branchColor = "gitClean"')
m("git-unstaged-sign", "segments.go", 'applyColor(ctx.Theme, "warning", "*"', 'applyColor(ctx.Theme, "warning", "+"')
m("git-staged-sign", "segments.go", 'applyColor(ctx.Theme, "success", "+"', 'applyColor(ctx.Theme, "success", "*"')
m("git-untracked-sign", "segments.go", 'applyColor(ctx.Theme, "muted", "?"', 'applyColor(ctx.Theme, "muted", "!"')
m("git-host-icon-ignored", "segments.go", 'if opts.HostIcon != nil && *opts.HostIcon {', 'if false {')
m("git-hidden-branch-icon", "segments.go", 'content = segColor(ctx, branchColor, prefix) + text', 'content = prefix + text')
m("git-no-branch-no-dirty", "segments.go", 'if branch == "" && !dirty {', 'if branch == "" {')
m("thinking-high-color", "segments.go", 'case "high":\n\t\tsemantic = "thinkingHigh"', 'case "high":\n\t\tsemantic = "thinkingXhigh"')
m("thinking-label-medium", "segments.go", '"medium": "med"', '"medium": "medium"')
m("queue-compacting-text", "segments.go", '"compact q "', '"compacting q "')
m("queue-blocked-text", "segments.go", '"blocked "+', '"block "+')
m("token-total-includes-cache", "segments.go", 'ctx.Usage.Input+ctx.Usage.Output+ctx.Usage.CacheRead+ctx.Usage.CacheWrite, icons().Tokens', 'ctx.Usage.Input+ctx.Usage.Output, icons().Tokens')
m("cost-subagent-added", "segments.go", 'cost := ctx.Usage.Cost + ctx.Usage.SubagentCost', 'cost := ctx.Usage.Cost')
m("cost-sub-text", "segments.go", 'return renderedSegment{segColor(ctx, "cost", "(sub)"), true}', 'return renderedSegment{segColor(ctx, "cost", "(subscription)"), true}')
m("cost-both-text", "segments.go", 'reported+" (sub)"', 'reported+" sub"')
m("cost-hidden-zero", "segments.go", 'if cost == 0 && !sub {', 'if cost == 0 {')
m("context-error-threshold", "segments.go", '*ctx.ContextPercent > 90', '*ctx.ContextPercent > 95')
m("context-warn-threshold", "segments.go", '*ctx.ContextPercent > 70', '*ctx.ContextPercent > 75')
m("context-approx-mark", "segments.go", 'approx = "~"', 'approx = "≈"')
m("context-auto-icon", "segments.go", 'if ctx.AutoCompactEnabled && icons.Auto != "" {', 'if icons.Auto != "" {')
m("context-percent-decimals", "segments.go", 'jsToFixed(*ctx.ContextPercent, 1)', 'jsToFixed(*ctx.ContextPercent, 0)')
m("context-custom-compaction", "segments.go", 'func contextPctSegment(ctx *segmentContext) renderedSegment {\n\tif ctx.CustomCompactionEnabled {', 'func contextPctSegment(ctx *segmentContext) renderedSegment {\n\tif false {')
m("context-total-window", "segments.go", 'if ctx.CustomCompactionEnabled || ctx.ContextWindow == 0 {', 'if ctx.CustomCompactionEnabled {')
m("time-spent-threshold", "segments.go", 'if elapsed < 1000 {', 'if elapsed < 2000 {')
m("time-12h-noon", "segments.go", 'hours %= 12\n\t\tif hours == 0 {', 'hours %= 12\n\t\tif false {')
m("time-pm", "segments.go", 'if hours >= 12 {\n\t\t\tsuffix = "pm"', 'if hours > 12 {\n\t\t\tsuffix = "pm"')
m("time-seconds", "segments.go", 'str += ":" + pad2(now.Second())', 'str += ":" + jsNumber(float64(now.Second()))')
m("session-short-id", "segments.go", 'if len(u) > 8 {\n\t\t\t\tu = u[:8]', 'if len(u) > 7 {\n\t\t\t\tu = u[:7]')
m("session-name-trim", "segments.go", 'if jsTrim(display) == "" {', 'if display == "" {')
m("hostname-split", "segments.go", 'name, _, _ := strings.Cut(hostnameFn(), ".")', 'name := hostnameFn()')
m("cache-read-hit-rate", "segments.go", 'hit = jsToFixed(cr/(in+cr)*100, 0)', 'hit = jsToFixed(cr/in*100, 0)')
m("cache-read-zero-input", "segments.go", 'if in+cr > 0 {', 'if in > 0 {')
m("cache-write-hidden", "segments.go", 'if ctx.Usage.CacheWrite == 0 {', 'if false {')
m("ext-status-isolation", "segments.go", 'parts[i] = "\\x1b[0m" + p + "\\x1b[0m"', 'parts[i] = p')
m("ext-status-hidden-keys", "segments.go", 'if ctx.HiddenStatusKeys[e.Key] {\n\t\t\tcontinue', 'if false {\n\t\t\tcontinue')
m("custom-prefix-separator", "segments.go", 'content = custom.Prefix + sepDot + content', 'content = custom.Prefix + " " + content')
m("custom-self-colorize", "segments.go", 'if custom.Color != "" && !custom.SelfColorize {', 'if custom.Color != "" {')
m("custom-missing-prefix", "segments.go", 'return renderedSegment{orStr(custom.Prefix, custom.ID), true}', 'return renderedSegment{custom.ID, true}')
m("shell-mode-visible", "segments.go", 'return notVisible() // the bash-mode editor', 'return renderedSegment{"shell", true} // the bash-mode editor')
# theme.go
m("hex-regex", "theme.go", '`^#[0-9a-fA-F]{6}$`', '`^#[0-9a-f]{6}$`')
m("rainbow-skip-colon", "theme.go", "if ch == ' ' || ch == ':' {", "if ch == ' ' {")
m("rainbow-index", "theme.go", 'rainbowColors[i%len(rainbowColors)]', 'rainbowColors[i%(len(rainbowColors)-1)]')
m("color-fallback-text", "theme.go", 'out, _ := th.Fg("text", text)', 'out, _ := th.Fg("dim", text)')
m("user-theme-priority", "theme.go", 'if c, ok := userThemeColors()[semantic]; ok {', 'if c, ok := userThemeColors()[semantic]; ok && false {')
m("user-theme-trim", "theme.go", 'if c := jsTrim(raw); c != "" {', 'if c := raw; c != "" {')
m("icon-override", "theme.go", '*icons.field(k) = v', '_ = v')
m("separator-chevron", "theme.go", 'return separatorDef{"›", "‹"}', 'return separatorDef{"‹", "›"}')
m("thinking-text-nerd", "theme.go", 'table := thinkingTextUnicode\n\tif hasNerdFonts() {', 'table := thinkingTextUnicode\n\tif false {')
# env.go
m("nerd-explicit-off", "env.go", 'case "0":\n\t\treturn false', 'case "0":\n\t\treturn true')
m("nerd-ghostty", "env.go", 'if os.Getenv("GHOSTTY_RESOURCES_DIR") != "" {', 'if false {')
m("nerd-term-program-set", "env.go", 'term, ok := os.LookupEnv("TERM_PROGRAM")\n\tif !ok {', 'term := os.Getenv("TERM_PROGRAM")\n\tif term == "" {')
m("agent-dir-trim", "env.go", 'jsTrim(configured) != ""', 'configured != ""')
m("agent-dir-tilde", "env.go", 'strings.HasPrefix(trimmed, "~/"):', 'strings.HasPrefix(trimmed, "~"):')
m("agent-sessions-legacy", "env.go", 'legacy != primary {', 'true {')
m("thinking-selection", "env.go", 'if s, ok := eventLevel.(string); ok {', 'if s, ok := contextLevel.(string); ok {')
# config.go
m("config-placement-case", "config.go", 'n = strings.ToLower(jsTrim(s))\n\t}\n\tif n == "above"', 'n = jsTrim(s)\n\t}\n\tif n == "above"')
m("config-custom-id-chars", "config.go", '`^[a-zA-Z0-9_-]+$`', '`^[a-zA-Z0-9_]+$`')
m("config-custom-default-position", "config.go", 'position := "right"', 'position := "left"')
m("config-hide-default", "config.go", 'HideWhenMissing:     !hasHide || hide,', 'HideWhenMissing:     hasHide && hide,')
m("config-exclude-default", "config.go", 'ExcludeFromStatuses: !hasExclude || exclude,', 'ExcludeFromStatuses: hasExclude && exclude,')
m("config-custom-dedupe", "config.go", 'out[i] = it\n\t\t\tcontinue', '_ = i\n\t\t\tcontinue')
m("config-layout-global-placement", "config.go", 'if placed[id] {\n\t\t\t\t\tinvalid = append', 'if false {\n\t\t\t\t\tinvalid = append')
m("config-layout-row-dedupe", "config.go", 'case !seen[id]:\n\t\t\t\tseen[id] = true', 'case true:\n\t\t\t\tseen[id] = true')
m("config-disabled-dedupe", "config.go", '} else if !seen[id] {\n\t\t\tseen[id] = true\n\t\t\tdisabled', '} else if true {\n\t\t\tseen[id] = true\n\t\t\tdisabled')
m("config-max-length-floor", "config.go", 'p.MaxLength = ptr(int(math.Floor(n)))', 'p.MaxLength = ptr(int(math.Ceil(n)))')
m("config-max-length-positive", "config.go", '!math.IsNaN(n) && n > 0 {\n\t\t\tp.MaxLength', '!math.IsNaN(n) {\n\t\t\tp.MaxLength')
m("config-welcome-default", "config.go", 'Welcome: o.vals["welcome"] != false,', 'Welcome: o.vals["welcome"] == true,')
m("config-merge-override", "config.go", 'func pick[T any](d, o *T) *T {\n\tif o != nil {', 'func pick[T any](d, o *T) *T {\n\tif o == nil {')
m("config-merge-layout-placed", "config.go", 'if !placed[id] {\n\t\t\t\t\tsegments = append(segments, id)', 'if true {\n\t\t\t\t\tsegments = append(segments, id)')
m("config-merge-disabled", "config.go", 'if !off[id] {\n\t\t\t\tout = append(out, id)', 'if true {\n\t\t\t\tout = append(out, id)')
m("config-notification-prefix", "config.go", 'strings.HasPrefix(strings.TrimLeftFunc(value, isJSSpace), "[")', 'strings.HasPrefix(value, "[")')
m("config-status-trailing", "config.go", '`(\\x1b\\[[0-9;]*m|\\s|·|[|])+$`', '`(\\s|·|[|])+$`')
m("config-setting-preset-object", "config.go", 'next := o.clone()\n\tnext.set("preset", preset)', 'next := newObject()\n\tnext.set("preset", preset)')
# core.go
m("core-project-settings-win", "core.go", 'merged.set(k, mergeSettings(bo, oo))', 'merged.set(k, mergeSettings(oo, bo))')
m("core-write-to-project", "core.go", 'if _, has := ps.vals["powerline"]; has {', 'if false {')
m("core-write-indent", "core.go", 'marshalJSON(settings, "  ")+"\\n"', 'marshalJSON(settings, "")+"\\n"')
m("core-refuse-malformed", "core.go", 'if gs == nil || ps == nil {', 'if false {')
m("core-warn-plural", "core.go", 'if n == 1 {\n\t\t\treturn ""', 'if n == 2 {\n\t\t\treturn ""')
m("core-warn-needs-ui", "core.go", 'if p.h.HasUI() {\n\t\tp.h.Notify(message, "warning")', 'if true {\n\t\tp.h.Notify(message, "warning")')
m("core-stash-clear", "core.go", 'if p.h.HasUI() {\n\t\tp.h.SetStatus(statusStash, nil)\n\t}', 'if false {\n\t\tp.h.SetStatus(statusStash, nil)\n\t}')
m("core-thinking-session-start", "core.go", 'p.currentThinking = p.h.ThinkingLevel()', 'p.currentThinking = nil')
m("core-status-widget-tui-only", "core.go", 'if p.h.Mode() == "tui" {\n\t\tp.ui.Widgets[widgetStatus]', 'if true {\n\t\tp.ui.Widgets[widgetStatus]')
m("core-placement-below", "core.go", 'if p.config.Placement == "below" {\n\t\tplacement = "belowEditor"', 'if p.config.Placement == "above" {\n\t\tplacement = "belowEditor"')
m("core-clear-before-install", "core.go", 'for _, key := range widgetKeys {\n\t\tp.h.ClearWidget(key)\n\t}\n\tp.ui = installedUI{Footer: true', 'p.ui = installedUI{Footer: true')
m("core-toggle-notify", "core.go", 'p.h.Notify("Powerline disabled", "info")', 'p.h.Notify("Powerline off", "info")')
m("core-preset-case", "core.go", 'n := strings.ToLower(jsTrim(value))\n\tif slices.Contains(presetNames, n) {', 'n := jsTrim(value)\n\tif slices.Contains(presetNames, n) {')
m("core-placement-toggle", "core.go", 'case p.config.Placement == "above":\n\t\t\t\tp.config.Placement = "below"', 'case p.config.Placement == "below":\n\t\t\t\tp.config.Placement = "below"')
m("core-layout-overhead", "core.go", 'const overhead = 2', 'const overhead = 1')
m("core-layout-sep-width", "core.go", 'sepWidth := visibleWidth(getSeparator(style).Left) + 2', 'sepWidth := visibleWidth(getSeparator(style).Left) + 1')
m("core-layout-fit", "core.go", 'if !over && cur+need <= available {', 'if !over && cur+need < available {')
m("core-layout-overflow-sticky", "core.go", 'if !over && cur+need <= available {', 'if (!over || true) && cur+need <= available {')
m("core-layout-secondary-break", "core.go", '\t\t} else {\n\t\t\tbreak\n\t\t}\n\t}\n\treturn buildContentFromParts', '\t\t} else {\n\t\t\tcontinue\n\t\t}\n\t}\n\treturn buildContentFromParts')
m("core-separator-color", "core.go", 'strings.Join(parts, " "+separatorAnsi+sep+ansiReset+" ")', 'strings.Join(parts, " "+sep+" ")')
m("core-config-separator", "core.go", 'style := p.config.Separator\n\tif style == "" {', 'style := ""\n\tif style == "" {')
m("core-status-width", "core.go", 'if visibleWidth(line) <= width {', 'if true {')
m("core-notification-only", "core.go", 'getNotificationExtensionStatuses(statuses, hidden)', 'getNotificationExtensionStatuses(nil, hidden)')
m("core-streaming-usage", "core.go", 'if p.isStreaming && p.liveUsage != nil {\n\t\tlatest = p.liveUsage', 'if false {\n\t\tlatest = p.liveUsage')
m("core-oauth", "core.go", 'UsingSubscription: model != nil && p.h.UsingOAuth(),', 'UsingSubscription: false,')
m("core-git-visible", "core.go", 'showGit := slices.Contains(all, "git")', 'showGit := true')
m("core-git-polling-default", "core.go", 'polling := "full"\n\t\tif gitOpts.Polling != nil {', 'polling := "off"\n\t\tif gitOpts.Polling != nil {')
m("core-custom-compaction-status", "core.go", 'if e.Key == "compact-policy" {', 'if e.Key == "compact" {')
m("core-thinking-from-session", "core.go", 'case stats.ThinkingLevelFromSession != nil:', 'case false:')
m("core-bash-git-patterns", "core.go", 'checkout|switch|branch\\s+-[dDmM]|merge|rebase|pull|reset|worktree', 'checkout|switch|merge|rebase|pull|reset|worktree')
# tokenstats / context usage / git / currency / json
m("stats-skip-error", "tokenstats.go", 'if sr := message["stopReason"]; sr == "error" || sr == "aborted" {', 'if sr := message["stopReason"]; sr == "error" {')
m("stats-last-assistant-tokens", "tokenstats.go", 'if usageTokenTotal(u) > 0 {\n\t\t\tst.LastAssistant', 'if true {\n\t\t\tst.LastAssistant')
m("stats-total-tokens", "tokenstats.go", 'if t, ok := fnum(u, "totalTokens"); ok && t != 0 {', 'if t, ok := fnum(u, "totalTokens"); ok && t != 0 && false {')
m("stats-subagent-slash", "tokenstats.go", 'e["customType"] == "subagent-slash-result"', 'e["customType"] == "subagent-slash"')
m("stats-subagent-tool-name", "tokenstats.go", 'msg["toolName"] == "subagent"', 'msg["toolName"] != ""')
m("stats-branch-cache-leaf", "tokenstats.go", '|| !sameString(c.leaf, leaf) {\n\t\tbranch', '|| false {\n\t\tbranch')
m("usage-percent-computed", "contextusage.go", 'percent := tokens / window * 100', 'percent := tokens / window')
m("usage-window-positive", "contextusage.go", '!finite(window) || window <= 0', '!finite(window)')
m("usage-unknown-fallback", "contextusage.go", 'if core != nil && core.Tokens == nil && unknownFallback != nil {', 'if false {')
m("usage-initial-estimate", "contextusage.go", 'n := (utf16Len(*systemPrompt) + 3) / 4', 'n := utf16Len(*systemPrompt) / 4')
m("git-locks-env", "git.go", 'out["GIT_OPTIONAL_LOCKS"] = "0"', 'out["GIT_OPTIONAL_LOCKS"] = "1"')
m("git-host-subdomain", "git.go", 'host == h[0] || strings.HasSuffix(host, "."+h[0])', 'host == h[0]')
m("git-polling-branch", "git.go", 'if polling != "full" {\n\t\treturn gitStatus{Branch: branch}', 'if polling == "off" {\n\t\treturn gitStatus{Branch: branch}')
m("git-provider-detached", "git.go", '*provider != "detached"', 'true')
m("currency-decimals", "currency.go", 'if currency == "JPY" || currency == "KRW" {', 'if currency == "JPY" {')
m("currency-missing-rate", "currency.go", 'return "-- " + currency', 'return "$0.00"')
m("currency-symbol", "currency.go", '"CNY": "¥"', '"CNY": "RMB"')
m("tofixed-tie", "jsutil.go", "if len(frac) > d && frac[d] >= '5' {", "if len(frac) > d && frac[d] > '5' {")
m("round-half-up", "jsutil.go", 'if x-r >= 0.5 {', 'if x-r > 0.5 {')
m("json-key-order", "jsjson.go", 'return append(idx, rest...)', 'return append(rest, idx...)')
m("json-empty-array", "jsjson.go", 'if len(x) == 0 {\n\t\t\tb.WriteString("[]")', 'if len(x) == 100 {\n\t\t\tb.WriteString("[]")')

# Review additions: the SDK adapter in an interactive host (adapter_test.go), the footer frame, pi-tui widths.
m("adapter-model-window", "extension.go", 'ContextWindow: float64(m.ContextWindow)}', 'ContextWindow: 0}')
m("adapter-autocompact-default", "extension.go", '\t\t}\n\t}\n\treturn true\n}', '\t\t}\n\t}\n\treturn false\n}')
m("adapter-oauth-provider", "extension.go", 'map[string]any{"id": m.ID, "provider": m.Provider}', 'map[string]any{"id": m.ID}')
m("adapter-session-name-error", "extension.go", 'if err != nil || n == nil {\n\t\treturn ""', 'if err == nil || n == nil {\n\t\treturn ""')
m("adapter-strict-theme", "extension.go", 'if !slices.Contains(piThemeTokens, token) {', 'if !slices.Contains(piThemeTokens, token) && false {')
m("adapter-top-placement", "extension.go", 'if placement, ok := ui.Widgets[widgetTop]; ok {\n\t\t_ = h.ctx.SetWidget(widgetTop, h.pl.renderTop(width), sdk.WidgetOptions{"placement": placement})', 'if _, ok := ui.Widgets[widgetTop]; ok {\n\t\t_ = h.ctx.SetWidget(widgetTop, h.pl.renderTop(width), sdk.WidgetOptions{"placement": "aboveEditor"})')
m("frame-not-published", "core.go", 'p.frame.Store(&footerFrame{ctx: c, ids: all, style: p.separatorStyle()})', '_ = c')
m("frame-style-default", "core.go", 'ids: all, style: p.separatorStyle()})', 'ids: all, style: "powerline"})')
m("width-tab", "text.go", "case r == '\\t':\n\t\treturn 3", "case r == '\\t':\n\t\treturn 1")
m("width-control", "text.go", 'case unicode.Is(unicode.Cc, r) || unicode.Is(unicode.Cf, r) ||', 'case unicode.Is(unicode.Cf, r) ||')
m("width-csi-any-final", "text.go", "case 'm', 'G', 'K', 'H', 'J':", "case 'm', 'G', 'K', 'H', 'J', 'A', 'l':")
m("width-apc", "text.go", "case ']', '_':", "case ']':")
m("width-osc-st", "text.go", "if s[j] == 0x1b && j+1 < len(s) && s[j+1] == '\\\\' {", "if false {")

bad = 0
for x in M:
    src = open(os.path.join(root, x["file"])).read()
    n = src.count(x["find"])
    if n != 1:
        print(f'{x["name"]}: find occurs {n} times in {x["file"]}', file=sys.stderr)
        bad += 1
if bad:
    sys.exit(1)
json.dump(M, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "w"), indent=1, ensure_ascii=False)
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "mutations.json"), "a").write("\n")
print(len(M), "mutations")
