// Generates extensions/powerline-footer/tables.go from the ORIGINAL modules (icons, separators, presets, theme).
// Usage (from components/powerline): PI_CODING_AGENT_PACKAGE=<Pi 1.0.0's pi-coding-agent> node --experimental-strip-types port/gen-tables.mjs | gofmt > extensions/powerline-footer/tables.go
import { pathToFileURL } from "node:url";
import { resolve } from "node:path";
const o = resolve(import.meta.dirname, "oracle");
const icons = await import(pathToFileURL(resolve(o, "icons.ts")).href);
const presets = await import(pathToFileURL(resolve(o, "presets.ts")).href);
const theme = await import(pathToFileURL(resolve(o, "theme.ts")).href);
const q = (s) => JSON.stringify(s).replace(/[\u007f-\uffff]/g, (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0")).replace(/\\u([0-9a-f]{4})/g, (m, h) => m);
const gostr = (s) => {
  let out = '"';
  for (const ch of s) {
    const cp = ch.codePointAt(0);
    if (ch === '"' || ch === "\\") out += "\\" + ch;
    else if (cp < 0x20 || cp === 0x7f) out += "\\x" + cp.toString(16).padStart(2, "0");
    else if (cp > 0x7e) out += cp > 0xffff ? "\\U" + cp.toString(16).padStart(8, "0") : "\\u" + cp.toString(16).padStart(4, "0");
    else out += ch;
  }
  return out + '"';
};
const camel = (k) => k.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase());
const iconKeys = Object.keys(icons.NERD_ICONS);
const sepKeys = Object.keys(icons.NERD_SEPARATORS);
let s = `// Code generated by port/gen-tables.mjs from the original's icons.ts, presets.ts and theme.ts; DO NOT EDIT.

package powerline_footer

type iconSet struct {
`;
for (const k of iconKeys) s += `\t${camel(k)} string\n`;
s += `}\n\nvar nerdIcons = iconSet{\n`;
for (const k of iconKeys) s += `\t${camel(k)}: ${gostr(icons.NERD_ICONS[k])},\n`;
s += `}\n\nvar asciiIcons = iconSet{\n`;
for (const k of iconKeys) s += `\t${camel(k)}: ${gostr(icons.ASCII_ICONS[k])},\n`;
s += `}\n\n// iconKeys maps theme.json icon names to the iconSet fields, in the original's order.\nvar iconKeys = []string{${iconKeys.map(gostr).join(", ")}}\n\nfunc (i *iconSet) field(key string) *string {\n\tswitch key {\n`;
for (const k of iconKeys) s += `\tcase ${gostr(k)}:\n\t\treturn &i.${camel(k)}\n`;
s += `\t}\n\treturn nil\n}\n\ntype separatorChars struct {\n`;
for (const k of sepKeys) s += `\t${camel(k)} string\n`;
s += `}\n\nvar nerdSeparators = separatorChars{\n`;
for (const k of sepKeys) s += `\t${camel(k)}: ${gostr(icons.NERD_SEPARATORS[k])},\n`;
s += `}\n\nvar asciiSeparators = separatorChars{\n`;
for (const k of sepKeys) s += `\t${camel(k)}: ${gostr(icons.ASCII_SEPARATORS[k])},\n`;
s += `}\n\nvar thinkingTextUnicode = map[string]string{\n`;
for (const [k, v] of Object.entries(icons.THINKING_TEXT_UNICODE)) s += `\t${gostr(k)}: ${gostr(v)},\n`;
s += `}\n\nvar thinkingTextNerd = map[string]string{\n`;
for (const [k, v] of Object.entries(icons.THINKING_TEXT_NERD)) s += `\t${gostr(k)}: ${gostr(v)},\n`;
import { readFileSync } from "node:fs";
// The theme tokens are those of the Pi the port targets (1.0.0), not of the original's dev dependency (0.84.4 lacks
// scrollbarTrack and scrollbarThumb): PI_CODING_AGENT_PACKAGE is the directory of Pi 1.0.0's @earendil-works/pi-coding-agent.
const piPkg = process.env.PI_CODING_AGENT_PACKAGE;
if (!piPkg) throw new Error("set PI_CODING_AGENT_PACKAGE to Pi 1.0.0's @earendil-works/pi-coding-agent directory");
const piVersion = JSON.parse(readFileSync(resolve(piPkg, "package.json"), "utf8")).version;
if (piVersion !== "1.0.0") throw new Error(`PI_CODING_AGENT_PACKAGE is pi-coding-agent ${piVersion}, not 1.0.0`);
const dts = readFileSync(resolve(piPkg, "dist/modes/interactive/theme/theme.d.ts"), "utf8");
const piTokens = [...dts.match(/export type ThemeColor =([^;]*);/)[1].matchAll(/"(\w+)"/g)].map((m) => m[1]);
const dc = theme.getDefaultColors();
s += `}\n\n// piThemeTokens are the ThemeColor tokens of Pi 1.0.0: its Theme.fg throws on any other.\nvar piThemeTokens = []string{${piTokens.map(gostr).join(", ")}}\n\n// semanticColors lists the semantic color names in the original's order.\nvar semanticColors = []string{${Object.keys(dc).map(gostr).join(", ")}}\n\nvar defaultColors = colorScheme{\n`;
for (const [k, v] of Object.entries(dc)) s += `\t${gostr(k)}: ${gostr(v)},\n`;
s += `}\n\nvar presetNames = []string{${Object.keys(presets.PRESETS).map(gostr).join(", ")}}\n\nvar presets = map[string]presetDef{\n`;
const strs = (a) => `[]string{${(a ?? []).map(gostr).join(", ")}}`;
const bool = (v) => (v === undefined ? "nil" : `ptr(${v})`);
for (const [name, p] of Object.entries(presets.PRESETS)) {
  s += `\t${gostr(name)}: {\n\t\tleft: ${strs(p.leftSegments)}, right: ${strs(p.rightSegments)}, secondary: ${strs(p.secondarySegments)},\n\t\tseparator: ${gostr(p.separator)},\n\t\tcolors: colorScheme{\n`;
  for (const [k, v] of Object.entries(p.colors)) s += `\t\t\t${gostr(k)}: ${gostr(v)},\n`;
  s += `\t\t},\n\t\toptions: segmentOptions{\n`;
  const so = p.segmentOptions ?? {};
  if (so.model) s += `\t\t\tModel: &modelOptions{${[so.model.showThinkingLevel !== undefined && `ShowThinkingLevel: ${bool(so.model.showThinkingLevel)}`, so.model.display && `Display: ptr(${gostr(so.model.display)})`].filter(Boolean).join(", ")}},\n`;
  if (so.path) s += `\t\t\tPath: &pathOptions{${[so.path.mode && `Mode: ptr(${gostr(so.path.mode)})`, so.path.maxLength !== undefined && `MaxLength: ptr(${so.path.maxLength})`].filter(Boolean).join(", ")}},\n`;
  if (so.git) s += `\t\t\tGit: &gitOptions{${["showBranch", "showStaged", "showUnstaged", "showUntracked"].filter((k) => so.git[k] !== undefined).map((k) => `${k[0].toUpperCase()}${k.slice(1)}: ptr(${so.git[k]})`).join(", ")}},\n`;
  if (so.time) s += `\t\t\tTime: &timeOptions{${[so.time.format && `Format: ptr(${gostr(so.time.format)})`, so.time.showSeconds !== undefined && `ShowSeconds: ptr(${so.time.showSeconds})`].filter(Boolean).join(", ")}},\n`;
  s += `\t\t},\n\t},\n`;
}
s += `}\n`;
process.stdout.write(s);
