// The generated npm source of each Piglet: what is rewritten, what is dropped, and the package.json PiG reads.
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it, after } from 'node:test';
import { parse } from 'yaml';
import { readManifests } from './generate-index.mjs';
import { buildPigletTree, npmPigletSource, pigletNpmName, pigletPackageJson } from './npm-piglets.mjs';
import { readPackages } from './packages.mjs';

const repository = 'MichaelKinsy/pigpen';
const names = readManifests().map(({ manifest }) => manifest.name);
const versions = new Map(readPackages().map(({ dir, manifest }) => [dir, manifest.version]));

describe('npmPigletSource', () => {
  it('turns every local Package into the npm Package at its own version', () => {
    for (const name of names) {
      const { data } = npmPigletSource(name);
      for (const [alias, source] of Object.entries(data.packages ?? {})) {
        const m = /^npm:@pi-in-go\/pigpen-([a-z0-9.-]+)@\^(\d+\.\d+\.\d+)$/.exec(source);
        assert.ok(m, `${name}: ${alias}: ${source}`);
        assert.equal(versions.get(m[1]), m[2], `${name}: ${alias}`);
      }
    }
  });
  it('leaves no local origin, extends or file path for a remote source to refuse', () => {
    for (const name of names) {
      const text = JSON.stringify(npmPigletSource(name).data);
      assert.doesNotMatch(text, /"local:/, name);
      assert.doesNotMatch(text, /"extends"/, name);
    }
  });
  it('flattens extends: pig-porter is the focused porter under its own name and description', () => {
    const { data, notes } = npmPigletSource('pig-porter');
    const base = npmPigletSource('pig-extension-porter').data;
    assert.equal(data.name, 'pig-porter');
    assert.notEqual(data.description, base.description);
    assert.deepEqual(data.packages, base.packages);
    assert.deepEqual(data.extensions, base.extensions);
    assert.match(notes.join(' '), /flattened/);
  });
  it('drops the local build fixture of pig-with-batteries and nothing else', () => {
    const authored = readManifests().find(({ manifest }) => manifest.name === 'pig-with-batteries').manifest.extensions.map((e) => e.name);
    const { data, notes } = npmPigletSource('pig-with-batteries');
    assert.deepEqual(authored.filter((n) => !data.extensions.some((e) => e.name === n)), ['seed-check']);
    assert.match(notes.join(' '), /fixture/);
  });
  it('keeps what makes the Piglet what it is', () => {
    for (const { manifest } of readManifests().filter(({ manifest: m }) => m.name !== 'pig-porter')) {
      const { data } = npmPigletSource(manifest.name);
      assert.equal(data.name, manifest.name);
      assert.deepEqual(data.release, manifest.release);
      assert.deepEqual(data.build, manifest.build);
      assert.deepEqual(data.discovery, manifest.discovery);
    }
  });
});

describe('the npm package of a Piglet', () => {
  it('is named, versioned and found the way the site searches', () => {
    for (const name of names) {
      const pkg = pigletPackageJson(name, { repository });
      assert.equal(pkg.name, pigletNpmName(name));
      assert.equal(pkg.name, `@pi-in-go/pigpen-piglet-${name}`);
      assert.equal(pkg.version, readManifests().find(({ manifest }) => manifest.name === name).manifest.release.version);
      assert.ok(pkg.keywords.includes('pig-piglet'));
      assert.equal(pkg.keywords.includes('pig-package'), false, 'a Piglet is classified by the most specific keyword; it carries only its own');
      assert.deepEqual(pkg.pig, { piglet: 'piglet.yaml' });
      assert.deepEqual(pkg.publishConfig, { access: 'public' });
      assert.equal(pkg.repository.directory, `piglets/${name}`);
      assert.ok(pkg.files.includes('piglet.yaml'));
      assert.equal('private' in pkg, false);
    }
  });
});

describe('buildPigletTree', () => {
  const out = mkdtempSync(join(tmpdir(), 'pigpen-npm-piglets-'));
  after(() => rmSync(out, { recursive: true, force: true }));
  it('writes a generated, parseable manifest, the README with the Binary pull command, the licence and the package.json', () => {
    const tree = buildPigletTree('herdr', out, { repository });
    const text = readFileSync(join(tree, 'piglet.yaml'), 'utf8');
    assert.match(text, /^# GENERATED by scripts\/npm-piglets\.mjs/);
    assert.equal(parse(text).name, 'herdr');
    const readme = readFileSync(join(tree, 'README.md'), 'utf8');
    assert.match(readme, /pig piglet pull 'github:MichaelKinsy\/pigpen\/herdr@0\.1\.0'/);
    assert.match(readme, /pig piglet add npm:@pi-in-go\/pigpen-piglet-herdr/);
    assert.match(readFileSync(join(tree, 'LICENSE'), 'utf8'), /MIT/);
    assert.equal(JSON.parse(readFileSync(join(tree, 'package.json'), 'utf8')).name, '@pi-in-go/pigpen-piglet-herdr');
  });
});
