package eq

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

// EnvSpec describes the isolated environment a porting session runs in (rule 17: no lane
// may read or write the user's ~/.pig, credentials or settings).
type EnvSpec struct {
	Root       string // scratch root: home, pighome and agent live under it
	GoRoot     string // the real Go toolchain, kept because a redirected HOME breaks version-manager shims
	GoCache    string
	GoModCache string
	NodeDir    string // directory of the real node executable
	Pig, Pi    string // host executables (PIG_BIN and PIGEQ_PIG, PIGEQ_PI)
	Source     string // a git checkout of the PiG source the pig was built from (PIG_SOURCE_ROOT)
	SDKDir     string // PiG's staged Go SDK (PIG_SDK_DIR, for mutate --unit)
	GoWork     string // a go.work mapping the SDK and the port's modules
}

func shq(s string) string { return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'" }

// EnvScript returns a POSIX shell script that isolates the session and exports the paths
// the porting workflow needs. Source it: `. env.sh`.
func EnvScript(s EnvSpec) string {
	var b strings.Builder
	line := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }
	export := func(name, value string) {
		if value != "" {
			line("export %s=%s", name, shq(value))
		}
	}
	line("# Isolated environment for a Pigpen porting session (generated by `pigeq env`).")
	line("# Nothing here reads or writes the real ~/.pig, auth.json or the user's settings.")
	if s.Root != "" {
		line("# pigeq env root: %s", s.Root)
	}
	line("# HOME is redirected below: after sourcing this, use absolute paths (\"~\" now means the scratch home).")
	line("# The real home stays in $PIGEQ_REAL_HOME.")
	line("export PIGEQ_REAL_HOME=\"${PIGEQ_REAL_HOME:-$HOME}\"")
	line("export GIT_TERMINAL_PROMPT=0")
	line("unset PIG_SDK_GO_ROOT") // the lane shell may point it at the real ~/.pig SDK cache
	export("HOME", filepath.Join(s.Root, "home"))
	export("PIG_HOME", filepath.Join(s.Root, "pighome"))
	export("PIG_CODING_AGENT_DIR", filepath.Join(s.Root, "agent"))
	export("PI_CODING_AGENT_DIR", filepath.Join(s.Root, "agent"))
	line("mkdir -p \"$HOME\" \"$PIG_HOME\" \"$PIG_CODING_AGENT_DIR\"")
	export("GOROOT", s.GoRoot)
	export("GOCACHE", s.GoCache)
	export("GOMODCACHE", s.GoModCache)
	var path []string
	if s.GoRoot != "" {
		path = append(path, filepath.Join(s.GoRoot, "bin"))
	}
	if s.NodeDir != "" {
		path = append(path, s.NodeDir)
	}
	if len(path) > 0 {
		line("export PATH=%s:\"$PATH\"", shq(strings.Join(path, ":")))
	}
	if s.Pig != "" {
		export("PIG_BIN", s.Pig)
		export("PIGEQ_PIG", s.Pig)
	}
	export("PIGEQ_PI", s.Pi)
	export("PIG_SOURCE_ROOT", s.Source)
	export("PIG_SDK_DIR", s.SDKDir)
	export("GOWORK", s.GoWork)
	return b.String()
}

// DiscoverToolchain fills GoRoot, GoCache, GoModCache and NodeDir from the real
// environment. Call it before isolating.
func DiscoverToolchain() (EnvSpec, error) {
	var s EnvSpec
	out, err := exec.Command("go", "env", "GOROOT", "GOCACHE", "GOMODCACHE").Output()
	if err != nil {
		return s, fmt.Errorf("go env: %w (Go is needed for source builds and the harness)", err)
	}
	f := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(f) != 3 {
		return s, fmt.Errorf("unexpected go env output %q", out)
	}
	s.GoRoot, s.GoCache, s.GoModCache = f[0], f[1], f[2]
	// process.execPath is the real node, where a version manager's shim would not be.
	if out, err := exec.Command("node", "-p", "process.execPath").Output(); err == nil {
		s.NodeDir = filepath.Dir(strings.TrimSpace(string(out)))
	}
	return s, nil
}

// sdkModule is the module path of PiG's public extension SDK.
const sdkModule = "github.com/MichaelKinsy/PiG/extensions/sdk"

// GoWork returns a go.work that maps PiG's SDK and the given modules. A port requires the SDK at
// v0.0.0, which PiG substitutes at build time, so a plain `go test` cannot resolve it. The SDK is
// a replace, not a use: with a third-party dependency in any module a go.work that only `use`s
// the SDK fails with "sdk@v0.0.0: unknown revision" (found by three ports).
func GoWork(sdk string, modules []string) string { return GoWorkFor(sdk, modules) }

// GoWorkFor is GoWork with the go directive taken from the highest `go` line among the SDK and the
// modules (at least 1.26): a module that requires a dependency built for go 1.26.0 is refused by a
// go.work that says `go 1.26`, which sorts below it.
func GoWorkFor(sdk string, modules []string) string {
	directive := "1.26"
	for _, dir := range append([]string{sdk}, modules...) {
		if v := goDirective(filepath.Join(dir, "go.mod")); v != "" && goVersionLess(directive, v) {
			directive = v
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "go %s\n\nuse (\n", directive)
	for _, m := range modules {
		fmt.Fprintf(&b, "\t%s\n", m)
	}
	fmt.Fprintf(&b, ")\n\nreplace %s => %s\n", sdkModule, sdk)
	// With the SDK a replace, a `use`d library Package that another module requires at v0.0.0 is not
	// resolved from the workspace (jev: "unknown revision components/<lib>/v0.0.0"). Giving every used
	// module a versioned replace to its own directory resolves it for every layout: a single module, a
	// library Package, a library Package that requires a library Package (pigpen-typesafe), and a
	// wrapper command that replaces its extension itself.
	for _, m := range modules {
		if path := goModulePath(filepath.Join(m, "go.mod")); path != "" {
			fmt.Fprintf(&b, "replace %s v0.0.0 => %s\n", path, m)
		}
	}
	return b.String()
}

var modulePathRE = regexp.MustCompile(`(?m)^module\s+(\S+)`)

func goModulePath(gomod string) string {
	b, err := os.ReadFile(gomod)
	if err != nil {
		return ""
	}
	if m := modulePathRE.FindSubmatch(b); m != nil {
		return string(m[1])
	}
	return ""
}

var goLineRE = regexp.MustCompile(`(?m)^go\s+([0-9][0-9.]*)\s*$`)

func goDirective(gomod string) string {
	b, err := os.ReadFile(gomod)
	if err != nil {
		return ""
	}
	if m := goLineRE.FindSubmatch(b); m != nil {
		return string(m[1])
	}
	return ""
}

// goVersionLess orders go directives as Go does: `1.26` sorts below `1.26.0`.
func goVersionLess(a, b string) bool {
	pa, pb := goVersionParts(a), goVersionParts(b)
	for i := 0; i < 3; i++ {
		if pa[i] != pb[i] {
			return pa[i] < pb[i]
		}
	}
	return false
}

func goVersionParts(v string) [3]int {
	parts := [3]int{0, 0, -1}
	for i, f := range strings.SplitN(v, ".", 3) {
		n, _ := strconv.Atoi(f)
		parts[i] = n
	}
	return parts
}

// WriteGoWork writes GoWork to path.
func WriteGoWork(path, sdk string, modules []string) error {
	return os.WriteFile(path, []byte(GoWork(sdk, modules)), 0o644)
}

// SDKPath asks the pig for its staged Go SDK directory, isolated under root so the derived
// SDK cache lands there and not in the real ~/.pig.
func SDKPath(pig, root string) (string, error) {
	cmd := exec.Command(pig, "reload", "--sdk-path")
	cmd.Env = append(os.Environ(),
		"HOME="+filepath.Join(root, "home"), "PIG_HOME="+filepath.Join(root, "pighome"),
		"PIG_CODING_AGENT_DIR="+filepath.Join(root, "agent"), "PI_CODING_AGENT_DIR="+filepath.Join(root, "agent"))
	cmd.Env = withoutEnv(cmd.Env, "PIG_SDK_GO_ROOT")
	for _, d := range []string{"home", "pighome", "agent"} {
		if err := os.MkdirAll(filepath.Join(root, d), 0o755); err != nil {
			return "", err
		}
	}
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%s reload --sdk-path: %w: %s", pig, err, strings.TrimSpace(stderr.String()))
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	return strings.TrimSpace(lines[len(lines)-1]), nil
}

func withoutEnv(env []string, name string) []string {
	var out []string
	for _, e := range env {
		if !strings.HasPrefix(e, name+"=") {
			out = append(out, e)
		}
	}
	return out
}

// SnapshotSource exports one revision of a PiG repository into out and makes it a
// one-commit git checkout, which PiG's native Binary builder requires (PIG_SOURCE_ROOT).
func SnapshotSource(from, rev, out string) error {
	if _, err := os.Stat(out); err == nil {
		return fmt.Errorf("%s exists: not overwriting", out)
	}
	if err := exec.Command("git", "-C", from, "rev-parse", "--verify", rev+"^{commit}").Run(); err != nil {
		return fmt.Errorf("%s is not a revision of %s", rev, from)
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	archive := exec.Command("git", "-C", from, "archive", rev)
	untar := exec.Command("tar", "-x", "-C", out)
	pipe, err := archive.StdoutPipe()
	if err != nil {
		return err
	}
	untar.Stdin = pipe
	var e1, e2 bytes.Buffer
	archive.Stderr, untar.Stderr = &e1, &e2
	if err := untar.Start(); err != nil {
		return err
	}
	if err := archive.Run(); err != nil {
		_ = untar.Wait()
		return fmt.Errorf("git archive: %w: %s", err, e1.String())
	}
	if err := untar.Wait(); err != nil {
		return fmt.Errorf("tar: %w: %s", err, e2.String())
	}
	git := func(args ...string) error {
		cmd := exec.Command("git", append([]string{"-c", "commit.gpgsign=false", "-c", "user.name=pigeq", "-c", "user.email=pigeq@localhost"}, args...)...)
		cmd.Dir = out
		if b, err := cmd.CombinedOutput(); err != nil {
			return errors.New("git " + strings.Join(args, " ") + ": " + strings.TrimSpace(string(b)))
		}
		return nil
	}
	for _, args := range [][]string{{"init", "-q"}, {"add", "-A"}, {"commit", "-qm", "snapshot of " + rev}} {
		if err := git(args...); err != nil {
			return err
		}
	}
	return nil
}

// CheckPiVersion requires the Pi used as the oracle to be the Pi version the pig is built to match
// (`pig --version` prints 0.3.0+0.87.1: PiG version plus Pi version). A pig that does not report
// one cannot be checked.
func CheckPiVersion(pi, pig string) error {
	out, err := exec.Command(pig, "--version").Output()
	if err != nil {
		return nil
	}
	_, want, ok := strings.Cut(strings.TrimSpace(string(out)), "+")
	if !ok || want == "" {
		return nil
	}
	got, err := exec.Command(pi, "--version").Output()
	if err != nil {
		return fmt.Errorf("%s --version: %w (the Pi oracle must run; node must be on PATH)", pi, err)
	}
	if have := strings.TrimSpace(string(got)); have != want {
		return fmt.Errorf("the Pi at %s is %s but %s is built to match Pi %s: use that version (for example `npm i @earendil-works/pi-coding-agent@%s` in a scratch directory)", pi, have, pig, want, want)
	}
	return nil
}
