"""Pydantic output models built from each request's question IDs and allowed answers.

The same models generate the provider's JSON schema and validate its response.
Aliases preserve arbitrary question IDs and choice labels without colliding with
Pydantic's field names. Provider schemas omit unsupported metadata and constraints;
the models still enforce those constraints locally.
"""

from collections.abc import Mapping
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter, create_model
from pydantic_core import to_json
from typesafe_sdk import (
    Choice,
    Noul,
    Questions,
    Score,
)

from system_one_adapter._utils.probability_normalization import AnswerMode

Question = Noul | Choice | Score

Probability = Annotated[float, Field(ge=0, le=1)]

_QUESTIONS_ADAPTER = TypeAdapter(dict[str, Annotated[Question, Field(discriminator="type")]])
_OUTPUT_CONFIG = ConfigDict(extra="forbid", strict=True, serialize_by_alias=True)

# Score and Choice questions are only meaningful with at least two outcomes to choose
# between.
_MIN_CRITERIA = 2


def convert_question_collection_to_validated_api_question_models(
    questions: Questions,
) -> dict[str, Question]:
    """Convert a question collection to validated API question models.

    Reject empty collections, convert dictionary questions to API model instances, and
    require at least two criteria for scores and choices.

    Args:
        questions: TypeSafe question collection.

    Returns:
        Questions using API model types, keyed by their original identifiers.

    Raises:
        ValueError: The collection is empty or a score or choice has fewer than
            two criteria.
        pydantic.ValidationError: A question does not match the SDK schema.
    """
    if not questions:
        raise ValueError("At least one question is required.")
    # Dump SDK models so mutable question fields are revalidated and JSON containers
    # are materialized before they become prompts or score legends.
    question_data = {
        key: question.model_dump(mode="json") if isinstance(question, (Noul, Choice, Score)) else question
        for key, question in questions.items()
    }
    validated = _QUESTIONS_ADAPTER.validate_python(question_data, strict=True)
    for question in validated.values():
        if isinstance(question, (Score, Choice)) and len(question.criteria) < _MIN_CRITERIA:
            raise ValueError("Score and choice questions require at least two criteria.")
    return validated


def create_llm_output_model(
    questions: Mapping[str, Question],
    llm_answer_mode: AnswerMode,
) -> type[BaseModel]:
    """Build the per-request output model: `{"answers": {<question id>: <answer>}}`.

    Each question contributes one field to the inner `answers` model, aliased to its
    question ID, whose type is generated by `_create_llm_answer_type_for_question`
    to pin the answer to that question's allowed values. See the module docstring for
    why this is generated per request instead of declared statically.

    Args:
        questions: Prepared questions keyed by question identifier.
        llm_answer_mode: Probability or discrete answer mode.

    Returns:
        A dynamic Pydantic model containing one answer per question.
    """
    answer_fields: dict[str, Any] = {}
    for index, (question_id, question) in enumerate(questions.items()):
        answer_type = _create_llm_answer_type_for_question(
            index,
            question,
            llm_answer_mode,
        )
        is_probability_map = llm_answer_mode == "probabilities" and isinstance(question, (Choice, Score))
        # Choice and Score probability answers are nested models emitted as `$ref`s.
        # Anthropic's structured output silently discards sibling keywords, which would
        # remove the question and criteria. Keep the reference site bare; the model
        # definition and its concrete properties carry that context instead.
        description = None if is_probability_map else _build_llm_output_field_description(question, llm_answer_mode)
        answer_fields[f"answer_{index}"] = (answer_type, Field(alias=question_id, description=description))

    answers_model = create_model(
        "TypeSafeAnswers",
        __config__=_OUTPUT_CONFIG,
        # Keep the description on the definition: providers may discard `$ref` siblings.
        __doc__="Exactly one answer per property below. Use these property names verbatim and do not add, rename, or nest them under any other key.",
        **answer_fields,
    )
    return create_model(
        "TypeSafeEvaluation",
        __config__=_OUTPUT_CONFIG,
        answers=(answers_model, ...),
    )


def create_raw_output_schema(output_model: type[BaseModel]) -> dict[str, Any]:
    """Create the self-contained JSON schema for the output model.

    Args:
        output_model: Dynamic model from `create_llm_output_model`.

    Returns:
        JSON schema with the root definition inlined and nested models in `$defs`.
    """
    return _sanitize_provider_schema(output_model.model_json_schema())


# Keywords the native structured-output modes do not accept and that the Pydantic model
# still enforces locally on decode: ``title`` is echoed back by OpenAI as an extra
# property (rejected by the ``extra=forbid`` schema), and Anthropic rejects the numeric
# bound keywords outright. The model is still told the ``[0, 1]`` range through the
# field descriptions and system prompt.
_UNSUPPORTED_SCHEMA_KEYWORDS = frozenset({"title", "minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum"})


def _sanitize_provider_schema(value: Any) -> Any:
    if isinstance(value, dict):
        sanitized = {}
        for key, item in value.items():
            if key in _UNSUPPORTED_SCHEMA_KEYWORDS:
                continue
            if key in {"properties", "$defs"}:
                # These mappings contain user-defined names, not schema keywords.
                sanitized[key] = {name: _sanitize_provider_schema(schema) for name, schema in item.items()}
            else:
                sanitized[key] = _sanitize_provider_schema(item)
        return sanitized
    if isinstance(value, list):
        return [_sanitize_provider_schema(item) for item in value]
    return value


def _create_llm_answer_type_for_question(
    index: int,
    question: Question,
    llm_answer_mode: AnswerMode,
) -> Any:
    """Build the answer type that pins one question to its allowed values.

    The type depends on the question's own data (its labels or rubric size), so it is
    generated per question:

    - Noul: `bool` (discrete) or a `[0, 1]` probability.
    - Score: an integer in `[0, n)` (discrete) or a model with one `[0, 1]`
      probability property per rubric level.
    - Choice: a `Literal` of the exact labels (discrete) or a model with one
      `[0, 1]` probability property per label.

    Each probability-map property is aliased to its label and carries the label's
    criterion as its schema description.
    """
    if isinstance(question, Noul):
        return bool if llm_answer_mode == "discrete" else Probability

    if isinstance(question, Score):
        if llm_answer_mode == "discrete":
            return Annotated[int, Field(ge=0, lt=len(question.criteria))]
        answers_and_criteria = [(str(score), criterion) for score, criterion in enumerate(question.criteria)]
    else:
        answers = list(question.criteria)
        if llm_answer_mode == "discrete":
            # A Literal built from the question's runtime labels.
            return Literal[tuple(answers)]  # pyrefly: ignore[invalid-literal]
        answers_and_criteria = list(question.criteria.items())

    # Put criteria on their concrete properties so they survive `$ref` transforms.
    probability_fields: dict[str, Any] = {
        f"probability_{answer_index}": (
            Probability,
            Field(alias=answer, description=_serialize_instruction_value_for_prompt(criterion)),
        )
        for answer_index, (answer, criterion) in enumerate(answers_and_criteria)
    }
    return create_model(
        f"ProbabilityMap{index}",
        __config__=_OUTPUT_CONFIG,
        __doc__=_build_llm_output_question_description(question, llm_answer_mode),
        **probability_fields,
    )


def _build_llm_output_field_description(
    question: Question,
    llm_answer_mode: AnswerMode,
) -> str:
    description = _build_llm_output_question_description(question, llm_answer_mode)

    if isinstance(question, Score):
        levels = "\n".join(
            f"{score} = {_serialize_instruction_value_for_prompt(criterion)}" for score, criterion in enumerate(question.criteria)
        )
        if llm_answer_mode == "discrete":
            return f"{description}\nScore levels, answer with the integer:\n{levels}"
        return f"{description}\nRequired probability keys:\n{levels}"

    if isinstance(question, Choice):
        choices = "\n".join(
            f"{answer} = {_serialize_instruction_value_for_prompt(criterion)}" for answer, criterion in question.criteria.items()
        )
        if llm_answer_mode == "discrete":
            return f"{description}\nChoice labels, answer with one label:\n{choices}"
        return f"{description}\nRequired probability keys:\n{choices}"

    if not isinstance(question, Noul) or question.criteria is None:
        return description

    true_criteria = _serialize_instruction_value_for_prompt(question.criteria.get("true"))
    false_criteria = _serialize_instruction_value_for_prompt(question.criteria.get("false"))
    return f"{description}\nTrue criteria: {true_criteria}\nFalse criteria: {false_criteria}"


def _build_llm_output_question_description(
    question: Question,
    llm_answer_mode: AnswerMode,
) -> str:
    description = _serialize_instruction_value_for_prompt(question.instructions)
    if isinstance(question, Noul) and llm_answer_mode == "probabilities":
        description = (
            "Probability that the answer is yes or the assertion is true. "
            "0 means no or false, 0.5 means uncertain, and 1 means yes or true.\n"
            f"Question: {description}"
        )
    elif isinstance(question, Score) and llm_answer_mode == "probabilities":
        description = f"Each property maps a rubric level to the probability that the document matches it.\nQuestion: {description}"
    elif isinstance(question, Choice) and llm_answer_mode == "probabilities":
        description = f"Each property maps an option to the probability that it is the best answer.\nQuestion: {description}"
    return description


def _serialize_instruction_value_for_prompt(value: Any) -> str:
    if value is None:
        return "No additional instructions."
    if isinstance(value, str):
        return value
    return to_json(value).decode()
